### ISSUE TITLE
Error in news wizard: Requests is not defined

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1002]
```
2018-06-29 08:40:50 UTC
   (56 min ago)
service-92840e94-4f22-4679-a9e9-743e5c280fb3@rogerth.at (***@niel.be)
Count: 1 - Version: web
```

```
description: Caught exception in global scope: Requests is niet gedefinieerd

errorMessage: Requests is niet gedefinieerd
in https://rogerth.at/static/js/solutions/sln-news.js at line 28:9
init@https://rogerth.at/static/js/solutions/sln-news.js:28:9
   {anonymous}()@(https://rogerth.at/static/js/solutions/sln-news.js:36:5)
c@https://rogerth.at/static/js/jquery-1.10.0.min.js:4:25959
   at p.fireWith (https://rogerth.at/static/js/jquery-1.10.0.min.js:4:26707)
ready@https://rogerth.at/static/js/jquery-1.10.0.min.js:4:3303
q@https://rogerth.at/static/js/jquery-1.10.0.min.js:4:715

mobicageVersion: web

occurenceCount: 1

platform: 0

platformVersion: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; rv:11.0) like Gecko
```

**Comment by bart-at-mobicage** [comment]
Also in sln.broadcast

```
2018-06-29 09:23:22 UTC
   (14 min ago)
service-d32fb0a9-cce3-4dbd-a81c-203bb1258e94@rogerth.at
Count: 1 - Version: web
```

```
description: Caught exception in sln.broadcast

errorMessage: undefined is not an object (evaluating 'Requests.getBroadcastOptions({cached: false}).then')
channelUpdates@https://dashboard.onzestadapp.be/static/js/solutions/sln-broadcast.js:622:66
https://dashboard.onzestadapp.be/static/js/solutions/sln-utils.js:817:29
each@https://dashboard.onzestadapp.be/static/js/jquery-1.10.0.min.js:4:5351
broadcast@https://dashboard.onzestadapp.be/static/js/solutions/sln-utils.js:815:19
process@https://dashboard.onzestadapp.be/static/js/solutions/sln-utils.js:833:34
_on_message@https://dashboard.onzestadapp.be/static/js/solutions/sln-utils.js:836:20
valueChanged@https://dashboard.onzestadapp.be/static/js/firebase-channel.js:32:27
valueChanged@https://www.gstatic.com/firebasejs/4.0.0/firebase-database.js:193:835
fc@https://www.gstatic.com/firebasejs/4.0.0/firebase-database.js:57:166
bf@https://www.gstatic.com/firebasejs/4.0.0/firebase-database.js:122:217
cf@https://www.gstatic.com/firebasejs/4.0.0/firebase-database.js:121:405
Gb@https://www.gstatic.com/firebasejs/4.0.0/firebase-database.js:212:289
[native code]
wd@https://www.gstatic.com/firebasejs/4.0.0/firebase-database.js:176:285
[native code]
wd@https://www.gstatic.com/firebasejs/4.0.0/firebase-database.js:166:366
https://www.gstatic.com/firebasejs/4.0.0/firebase-database.js:164:283
ag@https://www.gstatic.com/firebasejs/4.0.0/firebase-database.js:148:466
onmessage@https://www.gstatic.com/firebasejs/4.0.0/firebase-database.js:147:247

mobicageVersion: web

occurenceCount: 1

platform: 0

platformVersion: Mozilla/5.0 (iPad; CPU OS 11_2_6 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0 Mobile/15D100 Safari/604.1
```

**Comment by bart-at-mobicage** [comment]
Occurred for me when receiving a channel message after publishing

````
2018-06-29 15:18:56 UTC
   (1 min ago)
service-16ea3533-9aaa-4807-b5e6-a2494457812d@rogerth.at (bart@mobicage.com via shop)
Count: 1 - Version: web
```

```
description: Caught exception in sln.broadcast

errorMessage: Cannot read property 'then' of undefined
TypeError: Cannot read property 'then' of undefined
    at channelUpdates (https://rogerthat-server.appspot.com/static/js/solutions/sln-broadcast.js:622:66)
    at Function.<anonymous> (https://rogerthat-server.appspot.com/static/js/solutions/sln-utils.js:817:21)
    at Function.each (https://rogerthat-server.appspot.com/static/js/jquery-1.10.0.min.js:4:5347)
    at Object.broadcast (https://rogerthat-server.appspot.com/static/js/solutions/sln-utils.js:815:15)
    at process (https://rogerthat-server.appspot.com/static/js/solutions/sln-utils.js:833:25)
    at FirebaseChannel._on_message [as onMessage] (https://rogerthat-server.appspot.com/static/js/solutions/sln-utils.js:836:13)
    at FirebaseChannel.valueChanged (https://rogerthat-server.appspot.com/static/js/firebase-channel.js:32:18)
    at https://www.gstatic.com/firebasejs/4.0.0/firebase-database.js:193:831
    at fc (https://www.gstatic.com/firebasejs/4.0.0/firebase-database.js:57:165)
    at bf (https://www.gstatic.com/firebasejs/4.0.0/firebase-database.js:122:215)

mobicageVersion: web

occurenceCount: 1

platform: 0

platformVersion: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
```
