### ISSUE TITLE
Failed to get broadcast options 

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#1051]
```python
type object 'Product' has no attribute 'PRODUCT_EXTRA_CITY' (/base/data/home/apps/e~rogerthat-server/20180803t110202.411588585533225705/add_1_monkey_patches.py:144)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/20180803t110202.411588585533225705/mcfw/restapi.py", line 289, in run
    result = run(f, args, kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180803t110202.411588585533225705/mcfw/rpc.py", line 183, in run
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180803t110202.411588585533225705/mcfw/restapi.py", line 96, in wrapped
    return f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180803t110202.411588585533225705/mcfw/rpc.py", line 167, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180803t110202.411588585533225705/mcfw/rpc.py", line 145, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180803t110202.411588585533225705/solutions/common/restapi/__init__.py", line 472, in rest_get_broadcast_options
    extra_city_product_key = Product.create_key(Product.PRODUCT_EXTRA_CITY)
AttributeError: type object 'Product' has no attribute 'PRODUCT_EXTRA_CITY'
```

**Comment by bart-at-mobicage** [comment]
Fixed in ff6f6e1
