### ISSUE TITLE
Quotations

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/oca-backend#1063]
Add possibility to create quotations in the shop. Inherits from 'order'.

- [x] Create quotation
- [x] List quotations (with download and view button)

**Comment by bart-at-mobicage** [comment]
@lucasvanhalst 

`500 Internal Server Error` when opening shop
```
Traceback (most recent call last):
  File "/Users/bart/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/Users/bart/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/Users/bart/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/Users/bart/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/Users/bart/mobicage/git/oca-backend/build/shop/view.py", line 284, in dispatch
    return super(BizzManagerHandler, self).dispatch()
  File "/Users/bart/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/Users/bart/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/Users/bart/mobicage/git/oca-backend/build/lib/oauth2client/appengine.py", line 756, in check_oauth
    resp = method(request_handler, *args, **kwargs)
  File "/Users/bart/mobicage/git/oca-backend/build/shop/view.py", line 329, in get
    context = get_shop_context()
  File "/Users/bart/mobicage/git/oca-backend/build/shop/view.py", line 228, in get_shop_context
    'new_order_list']))
  File "/Users/bart/mobicage/git/oca-backend/build/shop/view.py", line 274, in render_js_templates
    with open(os.path.join(os.path.dirname(__file__), 'templates', 'js', '%s.html' % tmpl)) as f:
  File "/Users/bart/Downloads/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/stubs.py", line 285, in __init__
    super(FakeFile, self).__init__(filename, mode, bufsize, **kwargs)
IOError: [Errno 2] No such file or directory: '/Users/bart/mobicage/git/oca-backend/build/shop/templates/js/new_order_list.html'
```
