### ISSUE TITLE
Payconiq payments fail in the demo app

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1177]
```
2018-11-19 16:04:13.928 CET
Sending request to https://dev.payconiq.com/v2/transactions (/base/data/home/apps/e~rogerthat-server/20181119t141533.414097498671770724/rogerthat/bizz/payment/providers/payconiq/api.py:311)
{"currency":"EUR","amount":0,"description":"Payment OSA Bakker via Onze Stad App app\nRef.: _js_16d1cdd6-d887-ef61-287b-26fda81dbbd3","callbackUrl":"https://rogerth.at/payments/callbacks/payconiq/transaction/update?id=_js_16d1cdd6-d887-ef61-287b-26fda81dbbd3"}

2018-11-19 16:04:14.069 CET
Status:403 Content:  (/base/data/home/apps/e~rogerthat-server/20181119t141533.414097498671770724/rogerthat/bizz/payment/providers/payconiq/api.py:320)

2018-11-19 16:04:14.142 CET
Handled payments error (/base/data/home/apps/e~rogerthat-server/20181119t141533.414097498671770724/rogerthat/api/payment.py:177)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/20181119t141533.414097498671770724/rogerthat/api/payment.py", line 172, in _do_call
    result = call(app_user, *args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20181119t141533.414097498671770724/mcfw/rpc.py", line 167, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20181119t141533.414097498671770724/mcfw/rpc.py", line 145, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20181119t141533.414097498671770724/rogerthat/bizz/payment/__init__.py", line 373, in create_transaction
    return get_api_module(provider_id).create_transaction(app_user, params)
  File "/base/data/home/apps/e~rogerthat-server/20181119t141533.414097498671770724/mcfw/rpc.py", line 167, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20181119t141533.414097498671770724/mcfw/rpc.py", line 145, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20181119t141533.414097498671770724/rogerthat/bizz/payment/providers/payconiq/api.py", line 321, in create_transaction
    raise PaymentException(ErrorPaymentTO.UNKNOWN, get_lang(app_user))
PaymentException: Er is een onbekende fout opgetreden. Probeer het later nogmaals.
```

**Comment by lucasvanhalst** [comment]
The credentials for payconiq were wrong, I've updated them now so it should work again.
