### ISSUE TITLE
Syntax error in Aalter homescreen, unrecognized expression: #news|regional_news

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1222]
```
description: ScreenBrandingException:
- Exception logged by screenBranding of service-64b6aa50-f190-4bab-9bb2-f013fdf20ccf@rogerth.at
- Service menu item name: 
- Service menu item coords: [0, 0, 0]
Uncaught javascript exception in HTML-app:
isTrusted: true
message: Uncaught Error: Syntax error, unrecognized expression: #news|regional_news
filename: file:///data/user/0/com.mobicage.rogerthat.be.aalter/cache/branding/AB4DC278E12D2ED775E6A5B683C0C66CE4E4BC9A91F14EF6EFF76B2916E6D92D/jquery/jquery-1.11.0.min.js
lineno: 2
colno: 12713
error: Error: Syntax error, unrecognized expression: #news|regional_news
NONE: 0
CAPTURING_PHASE: 1
AT_TARGET: 2
BUBBLING_PHASE: 3
type: error
target: [object Window]
currentTarget: [object Window]
eventPhase: 2
bubbles: false
cancelable: true
defaultPrevented: false
composed: false
timeStamp: 1197.8999999992084
srcElement: [object Window]
returnValue: true
cancelBubble: false
path: [object Window]
composedPath: function composedPath() { [native code] }
stopPropagation: function stopPropagation() { [native code] }
stopImmediatePropagation: function stopImmediatePropagation() { [native code] }
preventDefault: function preventDefault() { [native code] }
initEvent: function initEvent() { [native code] }


errorMessage: java.lang.Exception
	at com.mobicage.rogerthat.util.logging.L.logToServer(L.java:158)
	at com.mobicage.rogerthat.util.logging.L.bug(L.java:116)
	at com.mobicage.rogerthat.util.ActionScreenUtils.logError(ActionScreenUtils.java:291)
	at com.mobicage.rogerthat.plugins.friends.ActionScreenActivity$JSInterface.logError(ActionScreenActivity.java:348)
	at com.mobicage.rogerthat.plugins.friends.ActionScreenActivity$JSInterface.invoke(ActionScreenActivity.java:236)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:379)
	at android.os.Looper.loop(Looper.java:144)
	at android.os.HandlerThread.run(HandlerThread.java:65)


mobicageVersion: 1.4301

occurenceCount: 1

platform: 1

platformVersion: HUAWEI/PRA-LX1/HWPRA-H:8.0.0/HUAWEIPRA-LX1/386(C432):user/release-keys (-) 26 (-) PRA-LX1
```

**Comment by lucasvanhalst** [comment]
do we have the original source code of this somewhere?

**Comment by RubenMattan** [comment]
More logs

```
02-21 08:22:59.787  5488  5488 D MC      : UI   | Executing JS: if (typeof rogerthat !== 'undefined') rogerthat._badgeUpdated({"count":1,"key":"news"})
02-21 08:22:59.793  5488  5488 D MC      : UI   | Executing JS: if (typeof rogerthat !== 'undefined') rogerthat._badgeUpdated({"count":0,"key":"messages"})
02-21 08:22:59.795  5488  5488 D MC      : UI   | Executing JS: if (typeof rogerthat !== 'undefined') rogerthat._badgeUpdated({"count":0,"key":"news|regional_news"})
02-21 08:22:59.797  5488  5488 I MC      : UI   | [BRANDING] LOG: script.min.js:31 | 1
02-21 08:22:59.797  5488  5488 I MC      : UI   | [BRANDING] LOG: script.min.js:32 | news
02-21 08:22:59.902  5488  5658 I MC      : ???? | Received action 'log/' with params {"e":"Uncaught javascript exception in HTML-app:\nisTrusted: true\nmessage: Uncaught Error: Syntax error, unrecognized expression: #news|regional_news\nfilename: file:\/\/\/data\/user\/0\/com.mobicage.rogerthat.osa.demo3\/cache\/branding\/973642369BFBA439AFE4D973F204F39BD9F13CF4399E9E30C04B8AA6049DC7FA\/jquery\/jquery-1.11.0.min.js\nlineno: 2\ncolno: 12713\nerror: Error: Syntax error, unrecognized expression: #news|regional_news\nNONE: 0\nCAPTURING_PHASE: 1\nAT_TARGET: 2\nBUBBLING_PHASE: 3\ntype: error\ntarget: [object Window]\ncurrentTarget: [object Window]\neventPhase: 2\nbubbles: false\ncancelable: true\ndefaultPrevented: false\ncomposed: false\ntimeStamp: 11916.400000000067\nsrcElement: [object Window]\nreturnValue: true\ncancelBubble: false\npath: [object Window]\ncomposedPath: function composedPath() { [native code] }\nstopPropagation: function stopPropagation() { [native code] }\nstopImmediatePropagation: function stopImmediatePropagation() { [native code] }\npreventDefault: function preventDefault() { [native code] }\ninitEvent: function initEvent() { [native code] }\n"}
```

**Comment by lucasvanhalst** [comment]
Pretty sure this was fixed months ago when we altered some icons
