### ISSUE TITLE
There is an option 'none' in the news action dropdown

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1334]
Check with @lucasvanhalst if you don't find it immediately.

<img width="841" alt="Screenshot 2019-05-15 at 13 59 48" src="https://user-images.githubusercontent.com/17762105/57774029-bec54d80-7719-11e9-8128-09862e250df2.png">

```
sln-errors.js:68 Missing translation for key 'none'
Error: Missing translation for key 'none'
    at Object.T (https://rogerthat-server.appspot.com/flex/:34:34)
    at Object.eval [as tmpl] (eval at o (https://rogerthat-server.appspot.com/static/js/jquery.tmpl.min.js:10:4207), <anonymous>:3:8185)
    at g (https://rogerthat-server.appspot.com/static/js/jquery.tmpl.min.js:10:438)
    at Function.tmpl (https://rogerthat-server.appspot.com/static/js/jquery.tmpl.min.js:10:2062)
    at https://rogerthat-server.appspot.com/static/js/solutions/sln-news-wizard.js:334:26
```

**Comment by lucasvanhalst** [comment]
That's intentional, else you cannot remove the button. Looks like the translation was accidentally deleted though.

**Comment by RubenMattan** [comment]
It was removed by https://github.com/our-city-app/oca-backend/pull/1266
