### ISSUE TITLE
Error when uploading PDF as static content

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1335]
```
2019-05-21 08:00:43.676 CEST
Request identity: service-d31c88b6-c955-4a46-9913-a8f60ebc2fb3@rogerth.at - Bart test merchant (bart@mobicage.com via shop) (WEB) (/base/data/home/apps/e~rogerthat-server/20190520t141255.418317586457930736/rogerthat/rpc/users.py:180)

2019-05-21 08:00:43.970 CEST
Uploaded pdf contains 11 pages (/base/data/home/apps/e~rogerthat-server/20190520t141255.418317586457930736/solutions/common/handlers/__init__.py:236)

2019-05-21 08:00:43.970 CEST
Error while trying to save static content PDF for user service-d31c88b6-c955-4a46-9913-a8f60ebc2fb3@rogerth.at (/base/data/home/apps/e~rogerthat-server/20190520t141255.418317586457930736/add_1_monkey_patches.py:144)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/20190520t141255.418317586457930736/solutions/common/handlers/__init__.py", line 246, in post
    pdf_bytes = pdf_stream.getvalue()
AttributeError: 'file' object has no attribute 'getvalue'
```

```
2019-05-20 19:06:46.186 CEST
Request identity: service-92840e94-4f22-4679-a9e9-743e5c280fb3@rogerth.at (WEB) (/base/data/home/apps/e~rogerthat-server/20190520t141255.418317586457930736/rogerthat/rpc/users.py:184)

2019-05-20 19:06:46.283 CEST
Uploaded pdf contains 6 pages (/base/data/home/apps/e~rogerthat-server/20190520t141255.418317586457930736/solutions/common/handlers/__init__.py:236)

2019-05-20 19:06:46.283 CEST
Error while trying to save static content PDF for user service-92840e94-4f22-4679-a9e9-743e5c280fb3@rogerth.at (/base/data/home/apps/e~rogerthat-server/20190520t141255.418317586457930736/add_1_monkey_patches.py:144)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/20190520t141255.418317586457930736/solutions/common/handlers/__init__.py", line 246, in post
    pdf_bytes = pdf_stream.getvalue()
AttributeError: 'file' object has no attribute 'getvalue'
```

**Comment by RubenMattan** [comment]
Fixed by using .read() instead of .getvalue()
