### ISSUE TITLE
Disable/remove apps

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/oca-backend#1349]
- Update service stats creator so that it ignores services of which expiredAt > 0 https://github.com/our-city-app/mobicage-backend/blob/b0bb0e0705c26f4d9a81c672b005d41881ec9b9c/src/rogerthat/bizz/job/service_stats.py#L52
- Send message to users that the app will disappear soon (app broadcast)
  - manually
- Gather emails from all merchants to message them
- Disable all services
- Add disabled property to 'App'
  - Omit disabled apps in the 'released apps' statistic
  - Don't allow registration when app is disabled
- remove from app store
  - manually
- remove from play store
  - manually

**Comment by bart-at-mobicage** [comment]
When a merchant logs in, he gets a **500 INTERNAL SERVER ERROR** thrown at his face. Because the default app id is None.

```
Expected an integer id or string name as argument 2; received None (a NoneType). (/base/data/home/apps/e~rogerthat-server/20190618t121658.418988304666886150/add_1_monkey_patches.py:144)
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/6a5167f0cae8960d/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/6a5167f0cae8960d/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/6a5167f0cae8960d/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/6a5167f0cae8960d/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/6a5167f0cae8960d/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/6a5167f0cae8960d/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20190618t121658.418988304666886150/solutions/flex/handlers.py", line 347, in get
    default_app = get_app_by_id(city_app_id)
  File "/base/data/home/apps/e~rogerthat-server/20190618t121658.418988304666886150/mcfw/rpc.py", line 169, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20190618t121658.418988304666886150/mcfw/rpc.py", line 147, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20190618t121658.418988304666886150/rogerthat/dal/app.py", line 82, in get_app_by_id
    return get_cached_model(App.create_key(app_id))
  File "/base/data/home/apps/e~rogerthat-server/20190618t121658.418988304666886150/rogerthat/models/__init__.py", line 193, in create_key
    return db.Key.from_path(App.kind(), app_id)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/6a5167f0cae8960d/python27/python27_lib/versions/1/google/appengine/api/datastore_types.py", line 532, in from_path
    'received %r (a %s).' % (i + 2, id_or_name, typename(id_or_name)))
BadArgumentError: Expected an integer id or string name as argument 2; received None (a NoneType).
2019-06-27 15:32:54.764 CEST
```

**Comment by bart-at-mobicage** [comment]
We also need a method to unregister all app users

**Comment by RubenMattan** [comment]
> We also need a method to unregister + archive all app users

Just loop over every user and call delete_account, no need to archive. Also make sure this function cannot be called for app_id **rogerthat**

**Comment by lucasvanhalst** [comment]
```
def _5():
  from solutions.common.job.delete_app import _5_unregister_accounts
  reason = u"""Uw gemeente/stad heeft beslist om niet langer in te zetten op de stadsapp. Het is niet meer mogelijk om deze te gebruiken."""
  return _5_unregister_accounts(app_id, reason)
```
(needs proper text)
