### ISSUE TITLE
Failing unittests

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1377]
- [ ] I18nTest.test_sln_placeholders: `AssertionError: Different placeholders in 2 languages`
```
Traceback (most recent call last):
  File "/Users/bart/mobicage/git/oca-backend/src-test/test/i18n/test_i18n.py", line 29, in test_sln_placeholders
    RogerthatI18nTest._test_placeholder(self, d)
  File "/Users/bart/mobicage/git/rogerthat-backend/src-test/rogerthat_tests/i18n/test_i18n.py", line 178, in _test_placeholder
    translation_dict['en'][key], lang, translation_dict[lang][key]))
AssertionError: Different placeholders in 2 languages:
en: Message scheduled for {{ datetime }}
nl: Nieuwsbericht gepland voor %(datetime)s
```

- [ ] LotteryTest.test_lottery: UnknownQueueError
```
Traceback (most recent call last):
  File "/Users/bart/mobicage/git/oca-backend/src-test/test/solutions/test_loyalty.py", line 128, in test_lottery
    service_user = self._create_service('test@email.com')
  File "/Users/bart/mobicage/git/oca-backend/src-test/test/solutions/test_loyalty.py", line 70, in _create_service
    organization_type=org_type)
  File "/Users/bart/mobicage/git/rogerthat-backend/src/mcfw/rpc.py", line 169, in typechecked_return
    result = f(*args, **kwargs)
  File "/Users/bart/mobicage/git/rogerthat-backend/src/mcfw/rpc.py", line 147, in typechecked_f
    return f(**kwargs)
  File "/Users/bart/mobicage/git/oca-backend/src/solutions/flex/bizz.py", line 230, in create_flex_service
    broadcast_to_users=broadcast_to_users)
  File "/Users/bart/mobicage/git/rogerthat-backend/src/mcfw/rpc.py", line 169, in typechecked_return
    result = f(*args, **kwargs)
  File "/Users/bart/mobicage/git/rogerthat-backend/src/mcfw/rpc.py", line 147, in typechecked_f
    return f(**kwargs)
  File "/Users/bart/mobicage/git/oca-backend/src/solutions/common/bizz/__init__.py", line 369, in create_or_update_solution_service
    _transactional=db.is_in_transaction(), _queue=FAST_QUEUE)
  File "/Users/bart/mobicage/git/rogerthat-backend/src/add_1_monkey_patches.py", line 332, in _new_deferred_defer
    return task.add(queue, transactional=transactional)
  File "/Users/bart/Applications/google-cloud-sdk/platform/google_appengine/google/appengine/api/taskqueue/taskqueue.py", line 1143, in add
    return self.add_async(queue_name, transactional).get_result()
  File "/Users/bart/Applications/google-cloud-sdk/platform/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/Users/bart/Applications/google-cloud-sdk/platform/google_appengine/google/appengine/api/taskqueue/taskqueue.py", line 1981, in ResultHook
    raise exception
UnknownQueueError
```

- [ ] TestEvents.test_get_period_dates: AssertionError: 1547458200 != 3600
```
Traceback (most recent call last):
  File "/Users/bart/mobicage/git/oca-backend/src-test/test/solutions/events.py", line 58, in test_get_period_dates
    self.assertEqual(1547458200, end_dates[0])
AssertionError: 1547458200 != 3600
```

**Comment by lucasvanhalst** [comment]
The UnknownQueueError one doesn't happen for me
