### ISSUE TITLE
Error in UiT nightly sync

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1382]
```
http://build.uitdatabank.be/api/events/search?format=json&pagelength=50&regio=Edegem&key=***&page=1&changedsince=2019-07-16T00.30 (/base/data/home/apps/e~rogerthat-server/20190716t170303.419642310741858713/solutions/common/bizz/cityapp.py:76)

process event with id: 3eb25322-078f-4cda-8b0d-67916021b8e3 (/base/data/home/apps/e~rogerthat-server/20190716t170303.419642310741858713/solutions/common/cron/events/uitdatabank.py:270)

Organizer info: {'lastupdated_by': u'bf324936-3a76-4aca-aa83-11e8d61011d1', 'organizer_name': u'***', 'created_by': u'bf324936-3a76-4aca-aa83-11e8d61011d1', 'organizer_cbdid': u'e3ff4022-d687-4eab-a168-850bd1cfa0e9'} (/base/data/home/apps/e~rogerthat-server/20190716t170303.419642310741858713/solutions/common/cron/events/uitdatabank.py:320)

organizer_settings: [] (/base/data/home/apps/e~rogerthat-server/20190716t170303.419642310741858713/solutions/common/cron/events/uitdatabank.py:334)

string indices must be integers (/base/data/home/apps/e~rogerthat-server/20190716t170303.419642310741858713/add_1_monkey_patches.py:144)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/20190716t170303.419642310741858713/solutions/common/cron/events/uitdatabank.py", line 89, in _process_cityapp_uitdatabank_events
    r['cdbid'], uitdatabank_actors, cap.uitdatabank_last_query or None)
  File "/base/data/home/apps/e~rogerthat-server/20190716t170303.419642310741858713/solutions/common/cron/events/uitdatabank.py", line 369, in _populate_uit_events
    if media_file['mediatype'] == 'photo':
TypeError: string indices must be integers
```

Event:
```
{u'availablefrom': u'2019-07-16T11:22:43',
 u'availableto': u'2019-09-08T15:00:00',
 u'calendar': {u'timestamps': {u'timestamp': {u'date': u'2019-09-08',
                                              u'timeend': u'15:00:00',
                                              u'timestart': u'09:00:00'}}},
 u'categories': {u'category': {u'catid': u'0.7.0.0.0',
                               u'type': u'eventtype',
                               u'value': u'Begeleide rondleiding'}},
 u'cdbid': u'3eb25322-078f-4cda-8b0d-67916021b8e3',
 u'contactinfo': {u'address': {u'physical': {u'city': u'Edegem',
                                             u'country': u'BE',
                                             u'gis': {u'xcoordinate': u'4.4399474',
                                                      u'ycoordinate': u'51.1564222'},
                                             u'housenr': u'65',
                                             u'street': u'Drie Eikenstraat',
                                             u'zipcode': u'2650'}},
                  u'mail': {u'reservation': u'true',
                            u'value': u'andre@masereelfonds.be'}},
 u'createdby': u'bf324936-3a76-4aca-aa83-11e8d61011d1',
 u'creationdate': u'2019-07-16T11:19:21',
 u'eventdetails': {u'eventdetail': {u'calendarsummary': u'zondag 8 september 2019 van 09:00 tot 15:00',
                                    u'lang': u'nl',
                                    u'longdescription': u'Na een lekker ontbijt stappen we naar Huis Hellemans. Hier bezoeken we een mooie tentoonstelling met fotokunst van Wim De Schamphelaere.  Aantal plaatsen zijn beperkt.<p class="uiv-source">Bron: <a href="http://www.uitinvlaanderen.be/agenda/e/bezoek-huis-hellemans-fotokunst/3eb25322-078f-4cda-8b0d-67916021b8e3">UiTinVlaanderen.be</a></p>',
                                    u'media': {u'file': {u'copyright': u'Rudi',
                                                         u'filename': u'295f82fa-fade-4475-b919-4a3aba9bc09a.jpeg',
                                                         u'filetype': u'jpeg',
                                                         u'hlink': u'https://io.uitdatabank.be/images/295f82fa-fade-4475-b919-4a3aba9bc09a.jpeg',
                                                         u'main': u'true',
                                                         u'mediatype': u'photo',
                                                         u'title': u'MF'}},
                                    u'price': {u'pricedescription': u'Basistarief: 15,00\xa0\u20ac; Leden en de gebruikelijke kortingcategorie\xebn: 10,00\xa0\u20ac',
                                               u'pricevalue': u'15.0'},
                                    u'shortdescription': u'Na een lekker ontbijt stappen we naar Huis Hellemans. Hier bezoeken we een mooie tentoonstelling met fotokunst van Wim De Schamphelaere.  Aantal plaatsen zijn beperkt.',
                                    u'title': u'Bezoek Huis Hellemans: fotokunst'}},
 u'externalurl': u'https://io.uitdatabank.be/event/3eb25322-078f-4cda-8b0d-67916021b8e3',
 u'lastupdated': u'2019-07-16T11:22:42',
 u'lastupdatedby': u'bf324936-3a76-4aca-aa83-11e8d61011d1',
 u'location': {u'address': {u'physical': {u'city': u'Edegem',
                                          u'country': u'BE',
                                          u'gis': {u'xcoordinate': u'4.4399474',
                                                   u'ycoordinate': u'51.1564222'},
                                          u'housenr': u'65',
                                          u'street': u'Drie Eikenstraat',
                                          u'zipcode': u'2650'}},
               u'label': {u'cdbid': u'e3bf19e3-f01c-4b03-9a95-5c6ed5cabc59',
                          u'value': u'Ons Huis'}},
 u'organiser': {u'label': {u'cdbid': u'e3ff4022-d687-4eab-a168-850bd1cfa0e9',
                           u'value': u'Masereelfonds Edegem'}},
 u'private': u'false',
 u'wfstatus': u'readyforvalidation'}
```

**Comment by bart-at-mobicage** [comment]
Already fixed @ b00ecca4628324f3439f06c5eaacc523d2141e89
