### ISSUE TITLE
Error when deleting a planned news item

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1404]
```
2019-08-08 14:54:13.470 CEST
[XX-SLOGv1] {"a":{"type_":"user"},"_dc":"eu6","e":"service-e00b5bc6-5fd6-4a18-95b2-756304295195@rogerth.at","f":"request_identification","_t":47501932402432,"m":"Request identification","T":"Thu, 08 Aug 2019 12:54:13.470","_i":"00c61b117c9a3e1a3f8d5010ffde1d63953b360113ba58bb8cdebb301e330a0a9a9bdf6b745e","_c":"US","t":1565268853.470162} (/base/data/home/apps/e~rogerthat-server/20190808t104229.420169665059093409/rogerthat/utils/__init__.py:475)

2019-08-08 14:54:13.470 CEST
Request identity: service-e00b5bc6-5fd6-4a18-95b2-756304295195@rogerth.at (WEB) (/base/data/home/apps/e~rogerthat-server/20190808t104229.420169665059093409/rogerthat/rpc/users.py:184)

2019-08-08 14:54:13.583 CEST
suspended generator _delete_tasklet(context.py:378) raised BadRequestError(Key path element must not be incomplete: [NewsItemImage: ]) (/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py:468)

2019-08-08 14:54:13.583 CEST
suspended generator delete(context.py:858) raised BadRequestError(Key path element must not be incomplete: [NewsItemImage: ]) (/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py:468)

2019-08-08 14:54:13.583 CEST
[XX-OFFLOADv1]{"function":"news.delete","status":false,"request_data":{"news_id":786147004,"service_identity":null},"timestamp":1565268853.583742,"response_data":{"error":{"message":"*****","code":1000}},"type":"api","user":"9e1dfd70f267ca872414e37e515c5d22"} (/base/data/home/apps/e~rogerthat-server/20190808t104229.420169665059093409/lib/log_offload/log_offload.py:48)
2019-08-08 14:54:13.590 CEST
[XX-OFFLOADv1]{"function":"/common/news/<news_id:\\d+>","status":false,"request_data":{"news_id":786147004},"timestamp":1565268853.590425,"response_data":"Key path element must not be incomplete: [NewsItemImage: ]","type":"web","user":"9e1dfd70f267ca872414e37e515c5d22"} (/base/data/home/apps/e~rogerthat-server/20190808t104229.420169665059093409/lib/log_offload/log_offload.py:48)

2019-08-08 14:54:13.590 CEST
Key path element must not be incomplete: [NewsItemImage: ] (/base/data/home/apps/e~rogerthat-server/20190808t104229.420169665059093409/add_1_monkey_patches.py:144)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/20190808t104229.420169665059093409/mcfw/restapi.py", line 289, in run
    result = run(f, args, kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20190808t104229.420169665059093409/mcfw/rpc.py", line 185, in run
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20190808t104229.420169665059093409/mcfw/restapi.py", line 96, in wrapped
    return f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20190808t104229.420169665059093409/mcfw/rpc.py", line 169, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20190808t104229.420169665059093409/mcfw/rpc.py", line 147, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20190808t104229.420169665059093409/solutions/common/restapi/news.py", line 109, in rest_delete_news
    delete_news(news_id, service_identity)
  File "/base/data/home/apps/e~rogerthat-server/20190808t104229.420169665059093409/solutions/common/bizz/news.py", line 808, in delete_news
    news.delete(news_id, service_identity)
  File "/base/data/home/apps/e~rogerthat-server/20190808t104229.420169665059093409/rogerthat/rpc/service.py", line 371, in wrapped
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20190808t104229.420169665059093409/mcfw/rpc.py", line 169, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20190808t104229.420169665059093409/mcfw/rpc.py", line 147, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20190808t104229.420169665059093409/rogerthat/service/api/news.py", line 115, in delete
    return news.delete(news_id, service_identity_user)
  File "/base/data/home/apps/e~rogerthat-server/20190808t104229.420169665059093409/mcfw/rpc.py", line 169, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20190808t104229.420169665059093409/mcfw/rpc.py", line 147, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20190808t104229.420169665059093409/rogerthat/bizz/news/__init__.py", line 1721, in delete
    ndb.delete_multi(to_delete)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 3987, in delete_multi
    for future in delete_multi_async(keys, **ctx_options)]
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 383, in get_result
    self.check_success()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 427, in _help_tasklet_along
    value = gen.throw(exc.__class__, exc, tb)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/ext/ndb/context.py", line 858, in delete
    yield self._delete_batcher.add(key, options)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 427, in _help_tasklet_along
    value = gen.throw(exc.__class__, exc, tb)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/ext/ndb/context.py", line 378, in _delete_tasklet
    yield self._conn.async_delete(options, datastore_keys)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 513, in _on_rpc_completion
    result = rpc.get_result()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 915, in get_result
    results = self.__rpcs[0].get_result()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 615, in get_result
    return self.__get_result_hook(self)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1993, in __delete_hook
    self.check_rpc_success(rpc)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1379, in check_rpc_success
    raise _ToDatastoreError(err)
BadRequestError: Key path element must not be incomplete: [NewsItemImage: ]

2019-08-08 14:54:13.689 CEST
memory_debugging:= start:312.2109375 end:312.2109375 instance_id:00c61b117c9a3e1a3f8d5010ffde1d63953b360113ba58bb8cdebb301e330a0a9a9bdf6b745e (/base/data/home/apps/e~rogerthat-server/20190808t104229.420169665059093409/rogerthat/wsgi/__init__.py:139)
```

**Comment by lucasvanhalst** [comment]
This shouldn't happen anymore but fixed now anyway https://github.com/our-city-app/mobicage-backend/commit/ca64fb94ff7425c3c82d853c4b0e84a3d3fd980f
