### ISSUE TITLE
Error when paying order with Stripe

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1455]
```
2019-09-16 12:55:27.182 CEST
Request identity: service-952f6d5a-8dad-4dd3-9332-4002b55adc5a@rogerth.at (WEB) (rogerthat/rpc/users.py:184)

2019-09-16 12:55:27.544 CEST
Automatic invoices are disabled (shop/bizz.py:2011)

2019-09-16 12:55:27.551 CEST
[XX-OFFLOADv1]{"function":"/common/store/order/pay","status":false,"request_data":{},"timestamp":1568631327.551192,"response_data":"type object 'Charge' has no attribute 'all'","type":"web","user":"feb9e474d70478f91e4a1a1a68a4a740"} (lib/log_offload/log_offload.py:48)

2019-09-16 12:55:27.551 CEST
type object 'Charge' has no attribute 'all' (add_1_monkey_patches.py:144)
Traceback (most recent call last):
  File "mcfw/restapi.py", line 289, in run
    result = run(f, args, kwargs)
  File "mcfw/rpc.py", line 185, in run
    result = function(*args, **kwargs)
  File "mcfw/restapi.py", line 96, in wrapped
    return f(*args, **kwargs)
  File "mcfw/rpc.py", line 169, in typechecked_return
    result = f(*args, **kwargs)
  File "mcfw/rpc.py", line 147, in typechecked_f
    return f(**kwargs)
  File "solutions/common/restapi/store.py", line 304, in pay_order
    return db.run_in_transaction_options(xg_on, trans)
  File "add_1_monkey_patches.py", line 234, in wrapped
    r = run(transaction_guid)
  File "add_1_monkey_patches.py", line 214, in run
    return _orig_run_in_transaction_options(options, *args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2635, in RunInTransactionOptions
    function, *args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2710, in _RunInTransactionInternal
    ok, result = _DoOneTry(function, args, kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2748, in _DoOneTry
    result = function(*args, **kwargs)
  File "solutions/common/restapi/store.py", line 295, in trans
    get_payed(customer.id, new_order, charge)
  File "mcfw/rpc.py", line 169, in typechecked_return
    result = f(*args, **kwargs)
  File "mcfw/rpc.py", line 147, in typechecked_f
    return f(**kwargs)
  File "shop/bizz.py", line 2107, in get_payed
    run_in_transaction(trans, True)
  File "rogerthat/utils/transactions.py", line 122, in run_in_transaction
    return function(*args, **kwargs)
  File "shop/bizz.py", line 2020, in trans
    stripe_charges = stripe.Charge.all(
AttributeError: type object 'Charge' has no attribute 'all'
```

**Comment by RubenMattan** [comment]
I guess you merged wrong? `master` is working perfectly

**Comment by bart-at-mobicage** [comment]
looks like I deployed staging instead of master 🙈
