### ISSUE TITLE
showNews is not defined

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#149]
```js

description: Caught exception in global scope: Uncaught ReferenceError: showNews is not defined

errorMessage: Uncaught ReferenceError: showNews is not defined
 in https://rogerth.at/static/js/solutions/sln-utils.js at line 173:15
ReferenceError: showNews is not defined
    at routingHandler (https://rogerth.at/static/js/solutions/sln-router.js:62:17)
    at https://rogerth.at/static/js/solutions/sln-router.js:23:9
    at x.event.dispatch (https://rogerth.at/static/js/jquery-1.10.0.min.js:5:13940)
    at jQuery.event.dispatch (https://rogerth.at/static/js/solutions/sln-utils.js:170:33)
    at v.handle (https://rogerth.at/static/js/jquery-1.10.0.min.js:5:10677)

mobicageVersion: web

occurenceCount: 35

platform: 0

platformVersion: Mozilla/5.0 (Linux; Android 4.4.4; T1-A21w Build/HuaweiMediaPad) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Safari/537.36
```

**Comment by lucasvanhalst** [comment]
8983257
