### ISSUE TITLE
Exception caught when loading cityapp settings if agenda module is not enabled

### ISSUE THREAD

**Issue by abom** [our-city-app/oca-backend#183]
When opening the dashboard, if the agenda module is not enabled for a service, the following exception will be raised:

> Caught exception in success handler of /common/cityapp/settings/load
> TypeError: $(...).data(...) is not a function
> TypeError: $(...).data(...) is not a function
>     at success (http://localhost:8080/static/js/solutions/cityapp.js:116:68)
>     at Object.options.success (http://localhost:8080/static/js/solutions/sln-utils.js:850:25)
>     at c (http://localhost:8080/static/js/jquery-1.10.0.min.js:4:25967)
>     at Object.fireWith [as resolveWith] (http://localhost:8080/static/js/jquery-1.10.0.min.js:4:26772)
>     at k (http://localhost:8080/static/js/jquery-1.10.0.min.js:6:14027)
>     at XMLHttpRequest.r (http://localhost:8080/static/js/jquery-1.10.0.min.js:6:18415)

**Comment by abom** [comment]
sln-cityapp.js references some elements that exist only if the agenda module is enabled for the service.

**Comment by abom** [comment]
I think that city app (uitdatabank agenda) settings can be shown in a different way or another tab?
