### ISSUE TITLE
Prospect export is becoming too big

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#187]
The mail can't be sent because the attachment is too big. We need to figure out a solution.

```
E 11:34:00.227
The request to API call datastore_v3.Put() was too large.
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/base/data/home/apps/s~mobicagecloudhr/3.398559108648932012/add_1_monkey_patches.py", line 270, in _new_deferred_run
    return func(*args, **kwds)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 180, in run_from_datastore
    ret = run(entity.data)
  File "/base/data/home/apps/s~mobicagecloudhr/3.398559108648932012/add_1_monkey_patches.py", line 270, in _new_deferred_run
    return func(*args, **kwds)
  File "/base/data/home/apps/s~mobicagecloudhr/3.398559108648932012/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/3.398559108648932012/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/3.398559108648932012/shop/business/prospect.py", line 277, in generate_prospect_export_excel
    attachment_name)
  File "/base/data/home/apps/s~mobicagecloudhr/3.398559108648932012/shop/bizz.py", line 1243, in send_email
    send_mail_via_mime(settings.senderEmail, to_emails, msg)
  File "/base/data/home/apps/s~mobicagecloudhr/3.398559108648932012/rogerthat/utils/__init__.py", line 246, in send_mail_via_mime
    deferred.defer(_send_mail_via_mime, from_, to, mime, _transactional=transactional, _queue=FAST_QUEUE)
  File "/base/data/home/apps/s~mobicagecloudhr/3.398559108648932012/add_1_monkey_patches.py", line 241, in _new_deferred_defer
    return _old_deferred_defer(f, *args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 280, in defer
    key = _DeferredTaskEntity(data=pickled).put()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/db/__init__.py", line 1077, in put
    return datastore.Put(self._entity, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 622, in Put
    return PutAsync(entities, **kwargs).get_result()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1879, in __put_hook
    self.check_rpc_success(rpc)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1369, in check_rpc_success
    rpc.check_success()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 579, in check_success
    self.__rpc.CheckSuccess()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_rpc.py", line 134, in CheckSuccess
    raise self.exception
RequestTooLargeError: The request to API call datastore_v3.Put() was too large.
```

**Comment by lucasvanhalst** [comment]
Perhaps we shouldn't send the email in a task. Just send it immediately, and should that fail restart the entire job to create the export. Not ideal but I don't think sending emails fails a lot.
