### ISSUE TITLE
VAT validation when creating services from city dashboard

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#232]
```
Failed to create service, unexpected BusinessException
Traceback (most recent call last):
  File "/base/data/home/apps/s~mobicagecloudhr/21.399410853077037633/solutions/common/restapi/services.py", line 216, in rest_put_service
    product_code, customer_id, vat)
  File "/base/data/home/apps/s~mobicagecloudhr/21.399410853077037633/shop/bizz.py", line 2582, in put_customer_with_service
    customer, email_changed, is_new_association = run_in_xg_transaction(trans1)
  File "/base/data/home/apps/s~mobicagecloudhr/21.399410853077037633/rogerthat/utils/transactions.py", line 103, in run_in_xg_transaction
    return db.run_in_transaction_options(xg_on, function, *args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/21.399410853077037633/add_1_monkey_patches.py", line 184, in wrapped
    r = run(transaction_guid)
  File "/base/data/home/apps/s~mobicagecloudhr/21.399410853077037633/add_1_monkey_patches.py", line 166, in run
    return _orig_run_in_transaction_options(options, *args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2647, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2667, in _DoOneTry
    result = function(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/21.399410853077037633/shop/bizz.py", line 2543, in trans1
    force=False, team_id=team_id)
  File "/base/data/home/apps/s~mobicagecloudhr/21.399410853077037633/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/21.399410853077037633/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/21.399410853077037633/shop/bizz.py", line 336, in create_or_update_customer
    vat = normalize_vat(country, vat)
  File "/base/data/home/apps/s~mobicagecloudhr/21.399410853077037633/shop/models.py", line 96, in normalize_vat
    return _vat_validators[country](vat)
  File "/base/data/home/apps/s~mobicagecloudhr/21.399410853077037633/shop/models.py", line 54, in _normalize_vat_be
    bizz_check(len(vat) == 12, "This vat number could not be validated for Belgium.")
  File "/base/data/home/apps/s~mobicagecloudhr/21.399410853077037633/rogerthat/utils/__init__.py", line 295, in bizz_check
    raise error_class(error_message)
BusinessException: This vat number could not be validated for Belgium.
```

Update the Belgium VAT before validation. Strip off all non-digit characters. Prefix with '0' if the VAT has 9 numbers. Prefix with 'BE' if this was missing.

The VAT number that was provided was "BE 500.928.685". Reformat to "BE0500928685" before validating.

**Comment by RubenMattan** [comment]
function: _normalize_vat_be
Only prefix with 0 is missing
