### ISSUE TITLE
Could not create new task for order via the dashboard

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#251]
```python
Queue: default
deferred.run(solutions.common.restapi.store.create_task_for_order,
             6175183782019072L,
             None,
             u'OSA.2017.304')

long() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/base/data/home/apps/s~mobicagecloudhr/24.399668009866338158/add_1_monkey_patches.py", line 283, in _new_deferred_run
    return func(*args, **kwds)
  File "/base/data/home/apps/s~mobicagecloudhr/24.399668009866338158/solutions/common/restapi/store.py", line 409, in create_task_for_order
    [RegioManagerTeam.create_key(customer_team_id), Prospect.create_key(prospect_id)])
  File "/base/data/home/apps/s~mobicagecloudhr/24.399668009866338158/shop/models.py", line 1198, in create_key
    prospect_id = long(prospect_id)
TypeError: long() argument must be a string or a number, not 'NoneType'
```

**Comment by RubenMattan** [comment]
Also the customer was not found in our database...

**Comment by abom** [comment]
@RubenMattan How it reached create_task_for_order if the customer is not there?

**Comment by RubenMattan** [comment]
I have no idea...
Maybe its better if i investigate further

**Comment by abom** [comment]
@RubenMattan  I think the task was created, then after that the customer has been deleted.
Should we just log that the order with number N is not longer valid as the customer has been deleted?

**Comment by RubenMattan** [comment]
Apparently the customer does exist but he does not have a prospect yet.
So you should create a prospect when prospect_id was None and pass it to the create_task_for_order defer

**Comment by bart-at-mobicage** [comment]
There's a method to create a prospect based on the customer model. Reuse this method for this purpose.

**Comment by abom** [comment]
Yes (create_prospect_from_customer), i have found it, thanks @RubenMattan  :)
