### ISSUE TITLE
[Shop] Failed to create service

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#256]
url: /internal/shop/rest/service/put

```python
Failed to create service
Traceback (most recent call last):
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/shop/view.py", line 1738, in save_service
    broadcast_to_users=[gusers.get_current_user()])
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/add_1_monkey_patches.py", line 205, in _allow_transaction_propagation
    return func(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/add_1_monkey_patches.py", line 184, in wrapped
    r = run(transaction_guid)
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/add_1_monkey_patches.py", line 166, in run
    return _orig_run_in_transaction_options(options, *args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2647, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2667, in _DoOneTry
    result = function(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/shop/bizz.py", line 674, in put_service
    search_enabled, qualified_identifier=service.email, broadcast_to_users=broadcast_to_users)
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/mcfw/rpc.py", line 126, in typechecked_f
    kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/mcfw/rpc.py", line 125, in <lambda>
    map(lambda arg: _check_type(arg, kwarg_types[arg], kwargs[arg], accept_missing=accept_missing, func=f),
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/mcfw/rpc.py", line 312, in _check_type
    % (name, str(checktype), i, type(x), x))
ValueError: apps: Not all items were of expected type (<type 'str'>, <type 'unicode'>). Encountered an item at index 1 with type <type 'NoneType'>: None.
```

**Comment by RubenMattan** [comment]
```python
Failed to create service
Traceback (most recent call last):
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/shop/view.py", line 1738, in save_service
    broadcast_to_users=[gusers.get_current_user()])
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/add_1_monkey_patches.py", line 205, in _allow_transaction_propagation
    return func(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/add_1_monkey_patches.py", line 184, in wrapped
    r = run(transaction_guid)
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/add_1_monkey_patches.py", line 166, in run
    return _orig_run_in_transaction_options(options, *args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2647, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2667, in _DoOneTry
    result = function(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/shop/bizz.py", line 646, in put_service
    is_demo = get_app(service.apps[0]).demo
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/rogerthat/bizz/app.py", line 68, in get_app
    return trans() if db.is_in_transaction() else db.run_in_transaction(trans)
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/rogerthat/bizz/app.py", line 63, in trans
    app = App.get(App.create_key(app_id))
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/rogerthat/models/__init__.py", line 195, in create_key
    return db.Key.from_path(App.kind(), app_id)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore_types.py", line 527, in from_path
    'received %r (a %s).' % (i + 2, id_or_name, typename(id_or_name)))
BadArgumentError: Expected an integer id or string name as argument 2; received None (a NoneType).
```
