### ISSUE TITLE
customer.subscription_type not set for legal entities

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#280]
Legal entities have different product codes. so `customer.subscription_type` is not being set: https://github.com/our-city-app/oca-backend/blob/master/src/shop/bizz.py#L522

**Comment by bart-at-mobicage** [comment]
Related issue

```
u'AS_OCAP'
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/34.400176030613108227/mcfw/restapi.py", line 156, in post
    result = self.run(f, parameters, kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/34.400176030613108227/mcfw/restapi.py", line 174, in run
    result = run(f, kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/34.400176030613108227/mcfw/rpc.py", line 165, in run
    result = function(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/34.400176030613108227/mcfw/restapi.py", line 70, in wrapped
    return f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/34.400176030613108227/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/34.400176030613108227/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/34.400176030613108227/shop/view.py", line 1504, in create_new_order
    create_order(customer_id, contact_id, items, replace, regio_manager_user=gusers.get_current_user())
  File "/base/data/home/apps/s~mobicagecloudhr/34.400176030613108227/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/34.400176030613108227/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/34.400176030613108227/shop/bizz.py", line 460, in create_order
    all_products[dependency].description(DEFAULT_LANGUAGE))
KeyError: u'AS_OCAP'
```
