### ISSUE TITLE
News image with wrong ratio

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#303]
Somehow users can bypass the image cropper. Sometimes I see error logs that the image ratio is not 160:60, but for example 1920:1080.

```
09:53:39.653
Image has an invalid ratio. (expected 16:6, got 1920:1080)

09:53:39.750
Image has an invalid ratio. (expected 16:6)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/38.400206554282260066/mcfw/restapi.py", line 156, in post
    result = self.run(f, parameters, kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/38.400206554282260066/mcfw/restapi.py", line 174, in run
    result = run(f, kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/38.400206554282260066/mcfw/rpc.py", line 165, in run
    result = function(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/38.400206554282260066/mcfw/restapi.py", line 70, in wrapped
    return f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/38.400206554282260066/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/38.400206554282260066/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/38.400206554282260066/solutions/common/restapi/news.py", line 104, in rest_put_news_item
    accept_missing=True)
  File "/base/data/home/apps/s~mobicagecloudhr/38.400206554282260066/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/38.400206554282260066/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/38.400206554282260066/solutions/common/bizz/news.py", line 237, in put_news_item
    news_item = run_in_xg_transaction(trans)
  File "/base/data/home/apps/s~mobicagecloudhr/38.400206554282260066/rogerthat/utils/transactions.py", line 103, in run_in_xg_transaction
    return db.run_in_transaction_options(xg_on, function, *args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/38.400206554282260066/add_1_monkey_patches.py", line 184, in wrapped
    r = run(transaction_guid)
  File "/base/data/home/apps/s~mobicagecloudhr/38.400206554282260066/add_1_monkey_patches.py", line 166, in run
    return _orig_run_in_transaction_options(options, *args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2647, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2667, in _DoOneTry
    result = function(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/38.400206554282260066/solutions/common/bizz/news.py", line 222, in trans
    news_item = news.publish(accept_missing=True, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/38.400206554282260066/rogerthat/rpc/service.py", line 337, in wrapped
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/38.400206554282260066/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/38.400206554282260066/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/38.400206554282260066/rogerthat/service/api/news.py", line 58, in publish
    target_audience, role_ids, accept_missing=True)
  File "/base/data/home/apps/s~mobicagecloudhr/38.400206554282260066/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/38.400206554282260066/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/38.400206554282260066/rogerthat/bizz/news.py", line 387, in put_news
    raise BusinessException('Image has an invalid ratio. (expected 16:6)')
BusinessException: Image has an invalid ratio. (expected 16:6)

```

**Comment by bart-at-mobicage** [comment]
This also occurred when saving the avatar. However, the image cropper is different than the one that's used in the news page.

```
/common/settings/publish_changes

09:11:47.104
Avatar Size: 135x150

09:11:47.104
[XX-OFFLOADv1] {"function":"system.put_avatar","request_data":{"image":"*****"},"success":false,"timestamp":1491289907,"response_data":null,"type":"api","user":"5a6bb6608eaddbd3741596306d7e6e48"}

09:11:47.107
Failure in common_provision
Traceback (most recent call last):
  File "/base/data/home/apps/s~mobicagecloudhr/40.400227091231861917/solutions/common/bizz/__init__.py", line 595, in common_provision
    bizz.provision(service_user, friends)
  File "/base/data/home/apps/s~mobicagecloudhr/40.400227091231861917/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/40.400227091231861917/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/40.400227091231861917/solutions/flex/bizz.py", line 113, in provision
    put_avatar_if_needed(service_user)
  File "/base/data/home/apps/s~mobicagecloudhr/40.400227091231861917/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/40.400227091231861917/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/40.400227091231861917/solutions/common/bizz/provisioning.py", line 363, in put_avatar_if_needed
    system.put_avatar(base64.b64encode(sln_avatar.picture))
  File "/base/data/home/apps/s~mobicagecloudhr/40.400227091231861917/rogerthat/rpc/service.py", line 337, in wrapped
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/40.400227091231861917/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/40.400227091231861917/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/40.400227091231861917/rogerthat/service/api/system.py", line 445, in put_avatar
    update_service_avatar(service_user, image1)
  File "/base/data/home/apps/s~mobicagecloudhr/40.400227091231861917/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/40.400227091231861917/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/40.400227091231861917/rogerthat/bizz/profile.py", line 768, in update_service_avatar
    raise AvatarImageNotSquareException()
AvatarImageNotSquareException: 60013 - Expected a square input image - {}
```
