### ISSUE TITLE
Error when posting news on facebook

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#304]
I don't have more info, because the ScheduledBroadcast object is already deleted.
@abom, do you have an idea what might have gone wrong? Let me know if you need more data from the datastore.

```
11:00:01.368
Queue: scheduled-queue
deferred.run(solutions.common.bizz.news.post_to_social_media_scheduled,
             '*****')
```

```
11:00:01.498
Post to facebook failed
Traceback (most recent call last):
  File "/base/data/home/apps/s~mobicagecloudhr/38.400206554282260066/solutions/common/bizz/facebook/__init__.py", line 26, in post_to_facebook
    fb.put_photo(image=image_source, message=message)
  File "/base/data/home/apps/s~mobicagecloudhr/38.400206554282260066/facebook/__init__.py", line 230, in put_photo
    method="POST")
  File "/base/data/home/apps/s~mobicagecloudhr/38.400206554282260066/facebook/__init__.py", line 314, in request
    raise GraphAPIError(result)
GraphAPIError: (#200) Requires manage_pages and publish_pages to manage the object
```

**Comment by abom** [comment]
It was working with the current permissions (manage_pages and publish_action).

I think that something has changed for Facebook graph API or our Facebook application, as manage_pages and publish_actions were enough to post to pages and user profile.

I got a similar exception:

```
Traceback (most recent call last):
  File "/home/abom/projects/oca-backend/build/solutions/common/bizz/facebook/__init__.py", line 28, in post_to_facebook
    fb.put_wall_post(message)
  File "/home/abom/projects/oca-backend/build/facebook/__init__.py", line 200, in put_wall_post
    **attachment)
  File "/home/abom/projects/oca-backend/build/facebook/__init__.py", line 181, in put_object
    method="POST")
  File "/home/abom/projects/oca-backend/build/facebook/__init__.py", line 314, in request
    raise GraphAPIError(result)
GraphAPIError: (#200) The user hasn't authorized the application to perform this action
```

I added the publish_pages permission to the required scopes when login to Facebook.
