### ISSUE TITLE
Failed to post news on facebook

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#332]
```python
Cannot get an extended facebook access token
Traceback (most recent call last):
  File "/base/data/home/apps/s~mobicagecloudhr/48.400715093888759503/solutions/common/bizz/news.py", line 324, in schedule_post_to_social_media
    facebook_access_token = facebook.extend_access_token(facebook_access_token)
  File "/base/data/home/apps/s~mobicagecloudhr/48.400715093888759503/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/48.400715093888759503/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/48.400715093888759503/solutions/common/bizz/facebook/__init__.py", line 58, in extend_access_token
    extended_token = fb.extend_access_token(app_id, app_secret)['access_token']
  File "/base/data/home/apps/s~mobicagecloudhr/48.400715093888759503/facebook/__init__.py", line 367, in extend_access_token
    args=args)
  File "/base/data/home/apps/s~mobicagecloudhr/48.400715093888759503/facebook/__init__.py", line 314, in request
    raise GraphAPIError(result)
GraphAPIError: fb_exchange_token parameter not specified
```

**Comment by abom** [comment]
It seems like this issue happens when an [empty access token is provided](https://github.com/mobolic/facebook-sdk/blob/master/test/test_facebook.py#L179), will check for access token if "Post to facebook" is checked.
