### ISSUE TITLE
Calculated recurrent charge of 0 euros

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#341]
We had hundreds of occurrences of this error since May 1st. Investigate why these subscriptions aren't skipped by the recurrent billing job.

```
02:02:11.049
X-Appengine-Taskretrycount:0, X-Appengine-Tasketa:1493683322.843847, X-Appengine-Taskname:1124644242293670065, X-Appengine-Taskexecutioncount:0, X-Appengine-Queuename:highload-worker-queue, X-Appengine-Current-Namespace:, X-Appengine-Country:ZZ

02:02:11.190
Creating recurrent charge for order OSA.2015.387 (6407739332886528: Gemeente Neerpelt)

02:02:11.238
Failed to create new charge: Calculated recurrent charge of 0 euros
Traceback (most recent call last):
  File "/base/data/home/apps/s~mobicagecloudhr/48.400715093888759503/shop/jobs/recurrentbilling.py", line 185, in _create_charge
    run_in_xg_transaction(trans)
  File "/base/data/home/apps/s~mobicagecloudhr/48.400715093888759503/rogerthat/utils/transactions.py", line 103, in run_in_xg_transaction
    return db.run_in_transaction_options(xg_on, function, *args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/48.400715093888759503/add_1_monkey_patches.py", line 184, in wrapped
    r = run(transaction_guid)
  File "/base/data/home/apps/s~mobicagecloudhr/48.400715093888759503/add_1_monkey_patches.py", line 166, in run
    return _orig_run_in_transaction_options(options, *args, **kwargs)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/api/datastore.py", line 2647, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/api/datastore.py", line 2667, in _DoOneTry
    result = function(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/48.400715093888759503/shop/jobs/recurrentbilling.py", line 124, in trans
    raise ZeroChargeException("Calculated recurrent charge of 0 euros")
ZeroChargeException: Calculated recurrent charge of 0 euros
```

**Comment by abom** [comment]
This exception is raised when the subscription total amount is zero, we can just skip them.

**Comment by bart-at-mobicage** [comment]
Normally the recurrent billing job shouldn't run for these charges. I thought we set charges to status PAID when the amount is 0.

**Comment by abom** [comment]
The job runs on signed orders, not charges, and free subscription orders are signed.
