### ISSUE TITLE
There is something wrong with a cropper ...

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#359]
```javascript
{"function":"/mobi/rest/system/log_error",
"request_data":{"timestamp":1494754987,
"errorMessage":"TypeError: undefined is not an object (evaluating 's.width')\n in https://rogerth.at/static/js/solutions/sln-utils.js at line 178:18\nhttps://rogerth.at/static/js/bower_components/cropper/dist/cropper.min.js:10:13341\neach@https://rogerth.at/static/js/jquery-1.10.0.min.js:4:5351\neach@https://rogerth.at/static/js/jquery-1.10.0.min.js:4:2003\npreview@https://rogerth.at/static/js/bower_components/cropper/dist/cropper.min.js:10:13300\noutput@https://rogerth.at/static/js/bower_components/cropper/dist/cropper.min.js:10:12232\nrenderCropBox@https://rogerth.at/static/js/bower_components/cropper/dist/cropper.min.js:10:12198\nchange@https://rogerth.at/static/js/bower_components/cropper/dist/cropper.min.js:10:19007\ncropMove@https://rogerth.at/static/js/bower_components/cropper/dist/cropper.min.js:10:16296\ndispatch@https://rogerth.at/static/js/jquery-1.10.0.min.js:5:13945\ndispatch@https://rogerth.at/static/js/solutions/sln-utils.js:175:38\nhandle@https://rogerth.at/static/js/jquery-1.10.0.min.js:5:10682",
"description":"*****",
"user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30"},
"success":false,
"timestamp":1494754990,
"response_data":"The transaction could not be committed. Please try again.",
"type":"web",
"user":"6437ccb3226d73e4041aab12734b66a7"}
```

**Comment by bart-at-mobicage** [comment]
> The transaction could not be committed. Please try again.

What was the server stacktrace?

**Comment by RubenMattan** [comment]
No server error the '/mobi/rest/system/log_error' was send to much

**Comment by abom** [comment]
Could we upgrade this cropper? or at least unify the cropper used everywhere?

**Comment by RubenMattan** [comment]
We should unify it. But its low prio

**Comment by abom** [comment]
We use the same cropper now, and this error still exists.

```
description: Caught exception in global scope: Uncaught TypeError: Cannot read property 'width' of undefined

errorMessage: Uncaught TypeError: Cannot read property 'width' of undefined
 in https://rogerthat-server.appspot.com/static/js/solutions/sln-utils.js at line 179:9
TypeError: Cannot read property 'width' of undefined
    at HTMLDivElement.<anonymous> (https://rogerthat-server.appspot.com/static/js/bower_components/cropper/dist/cropper.min.js:10:13341)
    at Function.each (https://rogerthat-server.appspot.com/static/js/jquery-1.10.0.min.js:4:5347)
    at init.each (https://rogerthat-server.appspot.com/static/js/jquery-1.10.0.min.js:4:1999)
    at v.preview (https://rogerthat-server.appspot.com/static/js/bower_components/cropper/dist/cropper.min.js:10:13296)
    at v.output (https://rogerthat-server.appspot.com/static/js/bower_components/cropper/dist/cropper.min.js:10:12225)
    at v.renderCropBox (https://rogerthat-server.appspot.com/static/js/bower_components/cropper/dist/cropper.min.js:10:12192)
    at v.render (https://rogerthat-server.appspot.com/static/js/bower_components/cropper/dist/cropper.min.js:10:7326)
    at v.resize (https://rogerthat-server.appspot.com/static/js/bower_components/cropper/dist/cropper.min.js:10:14814)
    at https://rogerthat-server.appspot.com/static/js/bower_components/cropper/dist/cropper.min.js:10:375
    at dispatch (https://rogerthat-server.appspot.com/static/js/jquery-1.10.0.min.js:5:13940)


```
