### ISSUE TITLE
Zip the thirdparty libraries

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#360]
Make the following changes to speed up deployment to appengine and also to speed up searching the code base. Be sure to test the code paths were the 3rdparty libraries are used (because in the past we tried to zip babel and pytz, but it didn't work)

- update `install.sh` to zip the contents of `rogerthat-backend/src/lib` after it executed `pip install -t ...` and finally remove the rest of the contents of the lib folder such that only the lib.zip file remains.
- in `appengine_config.py` add the lib zip instead of the lib folder.

**Comment by abom** [comment]
BTW, some searching tools like [ag](https://github.com/ggreer/the_silver_searcher) ignore the directories added to .gitignore by default.

**Comment by bart-at-mobicage** [comment]
When I tested this one, it worked. However, I had to revert commit 0d17e82cadfca28bc53f18077053b600ed1dc339 because it started failing after merging all other pull request about the data migration. Can you have a look?

```
ERROR    2017-06-16 08:00:16,715 add_1_monkey_patches.py:111] 

Traceback (most recent call last):
  File "/Users/bart/Applications/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Users/bart/Applications/google-cloud-sdk/platform/google_appengine/google/appengine/api/lib_config.py", line 354, in __getattr__
    self._update_configs()
  File "/Users/bart/Applications/google-cloud-sdk/platform/google_appengine/google/appengine/api/lib_config.py", line 290, in _update_configs
    self._registry.initialize()
  File "/Users/bart/Applications/google-cloud-sdk/platform/google_appengine/google/appengine/api/lib_config.py", line 165, in initialize
    import_func(self._modname)
  File "/Users/bart/mobicage/git/oca-backend/build/appengine_config.py", line 26, in <module>
    from add_2_zip_imports import dummy
  File "/Users/bart/mobicage/git/oca-backend/build/add_2_zip_imports.py", line 24, in <module>
    from rogerthat.bizz.authentication import get_user_scopes_from_request
  File "/Users/bart/mobicage/git/oca-backend/build/rogerthat/bizz/authentication.py", line 25, in <module>
    from jose import ExpiredSignatureError, jwt
  File "/Users/bart/mobicage/git/oca-backend/build/lib/lib.zip/jose/jwt.py", line 7, in <module>
  File "/Users/bart/mobicage/git/oca-backend/build/lib/lib.zip/jose/jws.py", line 8, in <module>
  File "/Users/bart/mobicage/git/oca-backend/build/lib/lib.zip/jose/jwk.py", line 11, in <module>
  File "/Users/bart/mobicage/git/oca-backend/build/lib/lib.zip/Crypto/PublicKey/RSA.py", line 78, in <module>
  File "/Users/bart/mobicage/git/oca-backend/build/lib/lib.zip/Crypto/Random/__init__.py", line 29, in <module>
  File "/Users/bart/mobicage/git/oca-backend/build/lib/lib.zip/Crypto/Random/_UserFriendlyRNG.py", line 38, in <module>
  File "/Users/bart/mobicage/git/oca-backend/build/lib/lib.zip/Crypto/Random/Fortuna/FortunaAccumulator.py", line 39, in <module>
  File "/Users/bart/mobicage/git/oca-backend/build/lib/lib.zip/Crypto/Random/Fortuna/FortunaGenerator.py", line 35, in <module>
  File "/Users/bart/mobicage/git/oca-backend/build/lib/lib.zip/Crypto/Util/Counter.py", line 59, in <module>
ImportError: cannot import name _counter
```

**Comment by abom** [comment]
It's working normally on my local environment, with the latest rogerthat/oca backends (they should include the data migration changes).

First i reverted the revert :), then removed rogerthat-backend/sr/lib and the build directory, then executed install.sh again.

`cd oca-backend`
`ls ../rogerthat-backend/src/lib/ `
`babel  lib.zip  ply  pytz`

`ls build/lib/`
`babel  lib.zip  ply  pytz`

**Comment by abom** [comment]
Running ./run_unit_tests.sh will fail with this error in case lib.zip exists (lxml module loaded from it).

```
======================================================================
ERROR: Failure: ImportError (cannot import name etree)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/abom/projects/rogerthat-backend/src-test/rogerthat_tests/__init__.py", line 140, in <module>
    init_env()
  File "/home/abom/projects/rogerthat-backend/src-test/rogerthat_tests/__init__.py", line 137, in init_env
    settings = get_server_settings()
  File "/home/abom/projects/rogerthat-backend/src/mcfw/cache.py", line 235, in wrapped
    memcache_result = mod_memcache.get(ck)  # @UndefinedVariable
  File "/usr/local/google_appengine/google/appengine/api/memcache/__init__.py", line 559, in get
    rpc = self.get_multi_async([key], namespace=namespace, for_cas=for_cas)
  File "/usr/local/google_appengine/google/appengine/api/memcache/__init__.py", line 607, in get_multi_async
    _add_name_space(request, namespace)
  File "/usr/local/google_appengine/google/appengine/api/memcache/__init__.py", line 127, in _add_name_space
    namespace = namespace_manager.get_namespace()
  File "/usr/local/google_appengine/google/appengine/api/namespace_manager/namespace_manager.py", line 88, in get_namespace
    name = _config.default_namespace_for_request()
  File "/usr/local/google_appengine/google/appengine/api/lib_config.py", line 351, in __getattr__
    self._update_configs()
  File "/usr/local/google_appengine/google/appengine/api/lib_config.py", line 287, in _update_configs
    self._registry.initialize()
  File "/usr/local/google_appengine/google/appengine/api/lib_config.py", line 160, in initialize
    import_func(self._modname)
  File "/home/abom/projects/rogerthat-backend/src/appengine_config.py", line 26, in <module>
    from add_2_zip_imports import dummy
  File "/home/abom/projects/rogerthat-backend/src/add_2_zip_imports.py", line 24, in <module>
    from rogerthat.bizz.authentication import get_user_scopes_from_request
  File "/home/abom/projects/rogerthat-backend/src/rogerthat/bizz/__init__.py", line 43, in <module>
    configure()
  File "/home/abom/projects/rogerthat-backend/src/rogerthat/bizz/__init__.py", line 19, in configure
    from rogerthat.bizz.friends import FRIEND_INVITATION_REQUEST, REQUEST_LOCATION_SHARING, UPDATE_PROFILE, \
  File "/home/abom/projects/rogerthat-backend/src/rogerthat/bizz/friends.py", line 47, in <module>
    from rogerthat.bizz.i18n import get_translator
  File "/home/abom/projects/rogerthat-backend/src/rogerthat/bizz/i18n.py", line 20, in <module>
    from lxml import etree
ImportError: cannot import name etree
```

lxml is loaded from lib.zip
```
(Pdb) import lxml
(Pdb) lxml
<module 'lxml' from '/home/abom/projects/rogerthat-backend/src/lib/lib.zip/lxml/__init__.pyc'>

```

when removing lib.zip it works normally (loaded directly from lib folder instead)
```
(Pdb) import lxml
(Pdb) lxml
<module 'lxml' from '/home/abom/projects/rogerthat-backend/src/lib/lxml/__init__.pyc'>

```

**Comment by lucasvanhalst** [comment]
The changes from #417 should make it so that the library folders aren't removed, which should make it so they don't get have to be uploaded again between new versions
