### ISSUE TITLE
Translation not found

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#385]
```python 
Translation key 'Scheduled timestamp must be in the future' not found in library 'common' for default language
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/6.402130754863793752/mcfw/restapi.py", line 282, in run
    result = run(f, args, kwargs)
  File "/base/data/home/apps/e~rogerthat-server/6.402130754863793752/mcfw/rpc.py", line 180, in run
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/6.402130754863793752/mcfw/restapi.py", line 92, in wrapped
    return f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/6.402130754863793752/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/6.402130754863793752/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/6.402130754863793752/solutions/common/restapi/news.py", line 110, in rest_put_news_item
    message = common_translate(sln_settings.main_language, SOLUTION_COMMON, e.message)
  File "/base/data/home/apps/e~rogerthat-server/6.402130754863793752/solutions/__init__.py", line 64, in translate
    raise ValueError("Translation key '%s' not found in library '%s' for default language" % (key, lib))
ValueError: Translation key 'Scheduled timestamp must be in the future' not found in library 'common' for default language```

**Comment by bart-at-mobicage** [comment]
catch the `InvalidScheduledTimestamp` exception and return a translated error message

**Comment by abom** [comment]
@bart-at-mobicage As no extra arguments is passed to this exception, i just added the translation.
And i have no idea how this exception is raised, the scheduling timestamp is double-checked at the client side :laughing:
