### ISSUE TITLE
Error in static content when adding a URL to an image

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#390]
A javascript error happens when adding the image. However, if you stop here and publish, then the branding looks ok. It contains the image.

When you try to add a hyperlink to the image, then pressing the OK button does nothing.

```
Uncaught DOMException: Failed to execute 'setBaseAndExtent' on 'Selection': There is no child at offset 1.
    at S.<anonymous> (http://rt.dev:8080/static/tinymce-4.2.6/tinymce.min.js:9:3017)
    at t.i [as fire] (http://rt.dev:8080/static/tinymce-4.2.6/tinymce.min.js:7:16998)
    at S.fire (http://rt.dev:8080/static/tinymce-4.2.6/tinymce.min.js:7:18880)
    at h.i (http://rt.dev:8080/static/tinymce-4.2.6/tinymce.min.js:9:10215)
    at i (http://rt.dev:8080/static/tinymce-4.2.6/tinymce.min.js:2:5859)
    at HTMLHtmlElement.m (http://rt.dev:8080/static/tinymce-4.2.6/tinymce.min.js:2:6199)
```

![screen shot 2017-06-29 at 12 07 47](https://user-images.githubusercontent.com/17762105/27682694-d93617fc-5cc3-11e7-9e59-3652ac1e15ad.png)

**Comment by abom** [comment]
I added an image, then added a hyperlink to it without any errors thrown. Do i need to it in a specific order/steps?
