### ISSUE TITLE
Transaction collision caused NPE when creating service

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#422]
```
10:05:47.530
FileObject 'html/img/osa_white_nl_250.jpg', Basepath: '/base/data/home/apps/e~rogerthat-server/21.402659118505646944/shop' (/base/data/home/apps/e~rogerthat-server/21.402659118505646944/lib/xhtml2pdf/util.py:517)

10:05:47.530
URLParts: ParseResult(scheme='', netloc='', path='/base/data/home/apps/e~rogerthat-server/21.402659118505646944/shop', params='', query='', fragment='') (/base/data/home/apps/e~rogerthat-server/21.402659118505646944/lib/xhtml2pdf/util.py:532)

10:05:50.020
Creating recommendation QR for service-f9b9c51f-689a-4dce-92d4-96ad476a643a@rogerth.at/+default+ (/base/data/home/apps/e~rogerthat-server/21.402659118505646944/rogerthat/bizz/service/__init__.py:611)

10:05:50.190
New avatar hash: 3C607337037C922671F00F46743FBF2F45320AE972064ECB3715FF7AE59264FF (/base/data/home/apps/e~rogerthat-server/21.402659118505646944/rogerthat/bizz/profile.py:913)

10:05:50.226
Coupling new user info@***.be to service-f9b9c51f-689a-4dce-92d4-***@rogerth.at (/base/data/home/apps/e~rogerthat-server/21.402659118505646944/rogerthat/bizz/service/__init__.py:2706)

10:05:50.251
New avatar hash: 3C607337037C922671F00F46743FBF2F45320AE972064ECB3715FF7AE59264FF (/base/data/home/apps/e~rogerthat-server/21.402659118505646944/rogerthat/bizz/profile.py:913)

10:05:50.282
Profile info@***.be removed from cache. (/base/data/home/apps/e~rogerthat-server/21.402659118505646944/rogerthat/models/__init__.py:551)

10:05:50.359
Profile service-f9b9c51f-689a-4dce-92d4-***@rogerth.at removed from cache. (/base/data/home/apps/e~rogerthat-server/21.402659118505646944/rogerthat/models/__init__.py:551)

10:05:50.361
Svc Identity service-f9b9c51f-689a-4dce-92d4-***@rogerth.at/+default+ removed from cache. (/base/data/home/apps/e~rogerthat-server/21.402659118505646944/rogerthat/models/__init__.py:1084)

10:05:50.363
Svc Identity service-f9b9c51f-689a-4dce-92d4-***@rogerth.at removed from cache. (/base/data/home/apps/e~rogerthat-server/21.402659118505646944/rogerthat/models/__init__.py:1087)

10:05:51.102
Transaction collision. Retrying...  (/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py:2688)

10:05:51.102
Transaction collision, retrying 1 .... (/base/data/home/apps/e~rogerthat-server/21.402659118505646944/add_1_monkey_patches.py:171)

10:05:51.247
Unhandled exception: 'NoneType' object has no attribute 'modules' (/base/data/home/apps/e~rogerthat-server/21.402659118505646944/solutions/common/bizz/service.py:125)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/21.402659118505646944/solutions/common/bizz/service.py", line 121, in put_customer_service
    run_in_xg_transaction(trans)
  File "/base/data/home/apps/e~rogerthat-server/21.402659118505646944/rogerthat/utils/transactions.py", line 103, in run_in_xg_transaction
    return db.run_in_transaction_options(xg_on, function, *args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/21.402659118505646944/add_1_monkey_patches.py", line 184, in wrapped
    r = run(transaction_guid)
  File "/base/data/home/apps/e~rogerthat-server/21.402659118505646944/add_1_monkey_patches.py", line 166, in run
    return _orig_run_in_transaction_options(options, *args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2647, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2667, in _DoOneTry
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/21.402659118505646944/solutions/common/bizz/service.py", line 118, in trans
    skip_email_check=skip_email_check)
  File "/base/data/home/apps/e~rogerthat-server/21.402659118505646944/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/21.402659118505646944/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/21.402659118505646944/shop/bizz.py", line 719, in put_service
    for m in sln_settings.modules:
AttributeError: 'NoneType' object has no attribute 'modules'

10:05:51.260
Could not save service service information (/base/data/home/apps/e~rogerthat-server/21.402659118505646944/add_1_monkey_patches.py:111)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/21.402659118505646944/solutions/common/restapi/services.py", line 245, in rest_put_service
    skip_email_check=True, rollback=is_new_service)
  File "/base/data/home/apps/e~rogerthat-server/21.402659118505646944/solutions/common/bizz/service.py", line 126, in put_customer_service
    raise e
AttributeError: 'NoneType' object has no attribute 'modules'

10:05:51.268
Failed to save new service service information, changes would be reverted... (/base/data/home/apps/e~rogerthat-server/21.402659118505646944/solutions/common/restapi/services.py:255)

10:05:51.269
[XX-OFFLOADv1] {"function":"/common/services/put","request_data":{"website":"www.***.be","city":"***","force":false,"name":"***","language":"nl","broadcast_types":["Evenementen","Infosessies","Kortingen","Nieuws"],"address1":"*** 23","address2":"","modules":["appointment","order","bulk_invite","static_content","ask_question","broadcast"],"telephone":"***","user_email":"info@***.be","organization_type":2,"facebook_page":"https://www.facebook.com/***/","vat":"***","zip_code":"***"},"success":true,"timestamp":1500278751,"response_data":{"errormsg":"Kon de dienst niet aanmaken. Probeer later opnieuw of contacteer onze klantendienst indien het probleem zich blijft voordoen.","warningmsg":null,"success":false},"type":"web","user":"2e257bc785b28ecdac5dc5a73d3923aa"} (/base/data/home/apps/e~rogerthat-server/21.402659118505646944/rogerthat/utils/__init__.py:396)
```

**Comment by RubenMattan** [comment]
This error occurs when the user double clicks save...
