### ISSUE TITLE
LargeImageError

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#432]
I thought the images were cropped in the browser?

```
/common/settings/logo/post

14:31:52.961
[XX-SLOGv1] {"a":{"type_":"user"},"_dc":"eu6","e":"service-a713b4bb-a00d-483f-8e8c-***@rogerth.at","f":"request_identification","_t":-16843968,"m":"Request identification","T":"Wed, 02 Aug 2017 12:31:52.960","_i":"00c61b117c57c349ac2cc8ef6e917066d58974005e5b07f3b59ecd5d019c05023fe9f8cc256db373","_c":"BE","t":1501677112.96088} (/base/data/home/apps/e~rogerthat-server/27.403099952722443275/rogerthat/utils/__init__.py:374)

14:31:52.961
Request identity: service-a713b4bb-a00d-483f-8e8c-***@rogerth.at (WEB) (/base/data/home/apps/e~rogerthat-server/27.403099952722443275/rogerthat/rpc/users.py:182)

14:31:53.997
Sending failure to the logged on users (service-a713b4bb-a00d-483f-8e8c-***@rogerth.at) channel (/base/data/home/apps/e~rogerthat-server/27.403099952722443275/add_1_monkey_patches.py:111)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/27.403099952722443275/solutions/common/handlers/__init__.py", line 124, in post
    image = img.execute_transforms(images.JPEG if image_type == 'jpeg' else images.PNG)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/images/__init__.py", line 810, in execute_transforms
    return rpc.get_result()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/images/__init__.py", line 898, in execute_transforms_hook
    raise _ToImagesError(e, self._blob_key)
LargeImageError
```

**Comment by abom** [comment]
The pull requests for refactoring the image upload are closed/unmerged.

https://github.com/our-city-app/oca-backend/pull/420
https://github.com/rogerthat-platform/rogerthat-backend/pull/232
