### ISSUE TITLE
Create unittests for lotteries

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#450]
... to prevent issues like this

```
argument 2 to map() must support iteration (/base/data/home/apps/e~rogerthat-server/28.403381765209054781/add_1_monkey_patches.py:109)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/base/data/home/apps/e~rogerthat-server/28.403381765209054781/add_1_monkey_patches.py", line 283, in _new_deferred_run
    return func(*args, **kwds)
  File "/base/data/home/apps/e~rogerthat-server/28.403381765209054781/solutions/common/cron/loyalty.py", line 449, in _pick_city_wide_lottery_winner
    db.run_in_transaction_options(xg_on, trans)
  File "/base/data/home/apps/e~rogerthat-server/28.403381765209054781/add_1_monkey_patches.py", line 184, in wrapped
    r = run(transaction_guid)
  File "/base/data/home/apps/e~rogerthat-server/28.403381765209054781/add_1_monkey_patches.py", line 166, in run
    return _orig_run_in_transaction_options(options, *args, **kwargs)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/api/datastore.py", line 2647, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/api/datastore.py", line 2667, in _DoOneTry
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/28.403381765209054781/solutions/common/cron/loyalty.py", line 421, in trans
    sln_cwl.winners_info = json.dumps(serialize_complex_value(winners_info, ExtendedUserDetailsTO, True))
  File "/base/data/home/apps/e~rogerthat-server/28.403381765209054781/mcfw/rpc.py", line 261, in serialize_complex_value
    return map(optimal_serializer, value)
  File "/base/data/home/apps/e~rogerthat-server/28.403381765209054781/mcfw/rpc.py", line 255, in optimal_serializer
    return serializer(val, skip_missing)
  File "/base/data/home/apps/e~rogerthat-server/28.403381765209054781/mcfw/rpc.py", line 446, in serializer
    not skip_missing or getattr(value, name) != MISSING]))
  File "/base/data/home/apps/e~rogerthat-server/28.403381765209054781/mcfw/rpc.py", line 442, in _serialize
    serialized_value = serialize_complex_value(attr, real_type, prop.list, skip_missing)
  File "/base/data/home/apps/e~rogerthat-server/28.403381765209054781/mcfw/rpc.py", line 261, in serialize_complex_value
    return map(optimal_serializer, value)
TypeError: argument 2 to map() must support iteration
```

https://github.com/our-city-app/oca-backend/commit/12d511d974f66fbff3a769737db160841b7a366b

**Comment by abom** [comment]
Some incomplete tests on this branch https://github.com/our-city-app/oca-backend/tree/450.cwl_tests
