### ISSUE TITLE
Missing translation for organizationType None

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#469]
/customers/signup?data=***&email=***

```
Missing translation for organizationType None (/base/data/home/apps/e~rogerthat-server/30.403591847514945743/add_1_monkey_patches.py:111)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/30.403591847514945743/shop/handlers.py", line 518, in get
    complete_customer_signup(email, data)
  File "/base/data/home/apps/e~rogerthat-server/30.403591847514945743/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/30.403591847514945743/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/30.403591847514945743/shop/bizz.py", line 2781, in complete_customer_signup
    signup.inbox_message_key = _send_new_customer_signup_message(service_user, signup)
  File "/base/data/home/apps/e~rogerthat-server/30.403591847514945743/shop/bizz.py", line 2681, in _send_new_customer_signup_message
    summary = get_signup_summary(lang, customer_signup, si.app_id)
  File "/base/data/home/apps/e~rogerthat-server/30.403591847514945743/shop/bizz.py", line 2644, in get_signup_summary
    org_type_name = ServiceProfile.localized_singular_organization_type(org_type, lang, customer_signup.city_customer.app_id)
  File "/base/data/home/apps/e~rogerthat-server/30.403591847514945743/rogerthat/models/__init__.py", line 895, in localized_singular_organization_type
    raise ValueError('Missing translation for organizationType %s' % organization_type)
ValueError: Missing translation for organizationType None
```

**Comment by abom** [comment]
Cannot reproduce.
