### ISSUE TITLE
Invalid email address entered during signup

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#471]
There were single quotes around the email address.

Happened multiple times. Did they enter it themselves? If so, decrease the prio to major.

11:11:29.055
```
{u"'***@skynet.be'": (501, 'Recipient syntax error')} (/base/data/home/apps/e~rogerthat-server/30.403591847514945743/add_1_monkey_patches.py:109)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/base/data/home/apps/e~rogerthat-server/30.403591847514945743/add_1_monkey_patches.py", line 283, in _new_deferred_run
    return func(*args, **kwds)
  File "/base/data/home/apps/e~rogerthat-server/30.403591847514945743/rogerthat/utils/__init__.py", line 306, in _send_mail_via_mime
    mailserver.sendmail(from_, to, mime_string)
  File "/base/data/home/runtimes/python27_experiment/python27_dist/lib/python2.7/smtplib.py", line 747, in sendmail
    raise SMTPRecipientsRefused(senderrs)
SMTPRecipientsRefused: {u"'***@skynet.be'": (501, 'Recipient syntax error')}
```

11:09:41.777
```
{u"'***@hotmail.com'": (501, 'Recipient syntax error')} (/base/data/home/apps/e~rogerthat-server/30.403591847514945743/add_1_monkey_patches.py:109)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/base/data/home/apps/e~rogerthat-server/30.403591847514945743/add_1_monkey_patches.py", line 283, in _new_deferred_run
    return func(*args, **kwds)
  File "/base/data/home/apps/e~rogerthat-server/30.403591847514945743/rogerthat/utils/__init__.py", line 306, in _send_mail_via_mime
    mailserver.sendmail(from_, to, mime_string)
  File "/base/data/home/runtimes/python27_experiment/python27_dist/lib/python2.7/smtplib.py", line 747, in sendmail
    raise SMTPRecipientsRefused(senderrs)
SMTPRecipientsRefused: {u"'***@hotmail.com'": (501, 'Recipient syntax error')}

```

**Comment by abom** [comment]
Neither the pattern or the email type for the input field allow this!

**Comment by bart-at-mobicage** [comment]
This happened via recommend
