### ISSUE TITLE
Show nice error to the user when static content is too big

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#507]
```
The value of property "html_content" is longer than 1048487 bytes. (/base/data/home/apps/e~rogerthat-server/33.403752247994015701/add_1_monkey_patches.py:111)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/33.403752247994015701/mcfw/restapi.py", line 283, in run
    result = run(f, args, kwargs)
  File "/base/data/home/apps/e~rogerthat-server/33.403752247994015701/mcfw/rpc.py", line 180, in run
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/33.403752247994015701/mcfw/restapi.py", line 93, in wrapped
    return f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/33.403752247994015701/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/33.403752247994015701/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/33.403752247994015701/solutions/common/restapi/__init__.py", line 233, in put_static_content
    bizz_put_static_content(service_user, static_content)
  File "/base/data/home/apps/e~rogerthat-server/33.403752247994015701/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/33.403752247994015701/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/33.403752247994015701/solutions/common/bizz/static_content.py", line 96, in put_static_content
    sln_settings = run_in_transaction(trans, True)
  File "/base/data/home/apps/e~rogerthat-server/33.403752247994015701/rogerthat/utils/transactions.py", line 122, in run_in_transaction
    return run_in_xg_transaction(function, *args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/33.403752247994015701/rogerthat/utils/transactions.py", line 103, in run_in_xg_transaction
    return db.run_in_transaction_options(xg_on, function, *args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/33.403752247994015701/add_1_monkey_patches.py", line 184, in wrapped
    r = run(transaction_guid)
  File "/base/data/home/apps/e~rogerthat-server/33.403752247994015701/add_1_monkey_patches.py", line 166, in run
    return _orig_run_in_transaction_options(options, *args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2647, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2667, in _DoOneTry
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/33.403752247994015701/solutions/common/bizz/static_content.py", line 90, in trans
    sc.put()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/db/__init__.py", line 1077, in put
    return datastore.Put(self._entity, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 622, in Put
    return PutAsync(entities, **kwargs).get_result()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1893, in __put_hook
    self.check_rpc_success(rpc)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1385, in check_rpc_success
    raise _ToDatastoreError(err)
BadRequestError: The value of property "html_content" is longer than 1048487 bytes.
```

**Comment by RubenMattan** [comment]
happened 8 times in the last 2 days..
