### ISSUE TITLE
functionalities page is empty on master. worked on staging.

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#558]
Normally, the only difference between master and staging was that I exported the translations. (in the mean time staging on master contain the same commits).

Can you investigate, @abom?

**Comment by abom** [comment]
I think the old [functionalities.tmpl](https://github.com/our-city-app/oca-backend/blob/e0b10774b538a202da8190e78f6bfdc2d0cc076f/src/solutions/common/templates/functionalities/functionalities.tmpl) file is deployed, not the latest [one](https://github.com/our-city-app/oca-backend/blob/master/src/solutions/common/templates/functionalities/functionalities.tmpl).


```
Caught exception in success handler of /common/functionalities/modules/activated
ReferenceError: FUNCTIONALITY_MODULES is not defined
ReferenceError: FUNCTIONALITY_MODULES is not defined
    at renderFunctionalities (https://rogerthat-server.appspot.com/static/js/solutions/sln-functionalities.js:98:16)
    at success (https://rogerthat-server.appspot.com/static/js/solutions/sln-functionalities.js:87:17)
    at Object.options.success (https://rogerthat-server.appspot.com/static/js/solutions/sln-utils.js:917:25)
    at c (https://rogerthat-server.appspot.com/static/js/jquery-1.10.0.min.js:4:25967)
    at Object.fireWith [as resolveWith] (https://rogerthat-server.appspot.com/static/js/jquery-1.10.0.min.js:4:26772)
    at k (https://rogerthat-server.appspot.com/static/js/jquery-1.10.0.min.js:6:14027)
    at XMLHttpRequest.r (https://rogerthat-server.appspot.com/static/js/jquery-1.10.0.min.js:6:18415)
```
