### ISSUE TITLE
GraphAPIError: Error validating access token: Session has expired

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#597]
How come we allowed scheduling a news item past the validity time of an access token?

```
19:00:00.160
Queue: scheduled-queue (/base/data/home/apps/e~rogerthat-server/50.404751828743137039/add_1_monkey_patches.py:317)
deferred.run(solutions.common.bizz.news.post_to_social_media_scheduled,
             '***')

19:00:01.112
Post to facebook failed (/base/data/home/apps/e~rogerthat-server/50.404751828743137039/add_1_monkey_patches.py:109)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/50.404751828743137039/solutions/common/bizz/facebook/__init__.py", line 56, in post_to_facebook
    fb.put_photo(image=image_source, message=message)
  File "/base/data/home/apps/e~rogerthat-server/50.404751828743137039/facebook/__init__.py", line 230, in put_photo
    method="POST")
  File "/base/data/home/apps/e~rogerthat-server/50.404751828743137039/facebook/__init__.py", line 314, in request
    raise GraphAPIError(result)
GraphAPIError: Error validating access token: Session has expired on Tuesday, 10-Oct-17 05:00:00 PDT. The current time is Thursday, 12-Oct-17 10:00:01 PDT.
```

**Comment by abom** [comment]
As i cannot find any related logs, i don't know why extending Facebook access token has failed.
Maybe we should show an error or a warning, because it tries to extend the token, and if it's failed, it only logs the error.

**Comment by abom** [comment]
A new server error that could be related

```
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/55.404931684938331203/solutions/common/bizz/news.py", line 330, in schedule_post_to_social_media
    facebook_access_token = facebook.extend_access_token(host, facebook_access_token)
  File "/base/data/home/apps/e~rogerthat-server/55.404931684938331203/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/55.404931684938331203/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/55.404931684938331203/solutions/common/bizz/facebook/__init__.py", line 72, in extend_access_token
    extended_token = fb.extend_access_token(app_id, app_secret)['access_token']
  File "/base/data/home/apps/e~rogerthat-server/55.404931684938331203/facebook/__init__.py", line 367, in extend_access_token
    args=args)
  File "/base/data/home/apps/e~rogerthat-server/55.404931684938331203/facebook/__init__.py", line 314, in request
    raise GraphAPIError(result)
GraphAPIError: The access token does not belong to application 1901272026796807
```
