### ISSUE TITLE
Errors for incoming REPAIR orders

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#606]
```
10:14:45.337
Queue: default (/base/data/home/apps/e~rogerthat-server/51.404775262369008682/add_1_monkey_patches.py:317)
deferred.run(solutions.common.bizz.repair._repair_order_received,
             users.User(email='service-e5d95a4d-a547-424e-904a-***@rogerth.at'),
             u'_js_5b8e9e30-f667-b461-4e42-302e9eba66',
             u'***@icloud.com',
             [<rogerthat.to.messaging.flow.FormFlowStepTO object at 0xf80d4990>, <rogerthat.to.messaging.flow.FormFlowStepTO object at 0xf80d4670>, <rogerthat.to.messaging.flow.FormFlowStepTO object at 0xf80d4ab0>, <rogerthat.to.messaging.flow.FormFlowStepTO object at 0xf5f8c2f0>, <rogerthat.to.messaging.flow.FormFlowStepTO object at 0xf5f8cef0>, <rogerthat.to.messaging.flow.MessageFlowStepTO object at 0xf5f8c990>],
             u'end_End',
             u'ahJlfnJvZ2VydGhhdC1zZXJ2ZXJybQsSCm1jLXRyYWNrZXIiN3NlcnZpY2UtZTVkOTVhNGQtYTU0Ny00MjRlLTkwNGEtYjhmOTY5Y2Q5NjJhQHJvZ2VydGguYXQMCxIRTWVzc2FnZUZsb3dEZXNpZ24iD3JlcG9ydC1jYXJkLXNhbQw',
             u'_js_d4c314f9-f9c-bb5a-5ed2-58a330942d82',
             u'__sln__.repair',
             u'15323644-880e-429c-b482-e3f8cac373d6',
             u'flush_flush',
             u'ahJlfnJvZ2VydGhhdC1zZXJ2ZXJybQsSCm1jLXRyYWNrZXIiN3NlcnZpY2UtZTVkOTVhNGQtYTU0Ny00MjRlLTkwNGEtYjhmOTY5Y2Q5NjJhQHJvZ2VydGguYXQMCxIRTWVzc2FnZUZsb3dEZXNpZ24iD3JlcG9ydC1jYXJkLXNhbQw',
             u'+default+',
             [<rogerthat.to.service.UserDetailsTO object at 0xf5f8c570>])

10:14:45.338
_flow_member_result_repair_order:  (/base/data/home/apps/e~rogerthat-server/51.404775262369008682/solutions/common/bizz/repair.py:57)
 [<rogerthat.to.messaging.flow.FormFlowStepTO object at 0xf80d4990>, <rogerthat.to.messaging.flow.FormFlowStepTO object at 0xf80d4670>, <rogerthat.to.messaging.flow.FormFlowStepTO object at 0xf80d4ab0>, <rogerthat.to.messaging.flow.FormFlowStepTO object at 0xf5f8c2f0>, <rogerthat.to.messaging.flow.FormFlowStepTO object at 0xf5f8cef0>, <rogerthat.to.messaging.flow.MessageFlowStepTO object at 0xf5f8c990>]

10:14:45.338
 (/base/data/home/apps/e~rogerthat-server/51.404775262369008682/add_1_monkey_patches.py:123)
  Locals: 
  - name: message_remarks
  - step: <rogerthat.to.messaging.flow.FormFlowStepTO object at 0xf80d4990>
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/base/data/home/apps/e~rogerthat-server/51.404775262369008682/add_1_monkey_patches.py", line 322, in _new_deferred_run
    return func(*args, **kwds)
  File "/base/data/home/apps/e~rogerthat-server/51.404775262369008682/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/51.404775262369008682/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/51.404775262369008682/solutions/common/bizz/repair.py", line 59, in _repair_order_received
    remarks = _get_value(steps[0], u'message_remarks')
  File "/base/data/home/apps/e~rogerthat-server/51.404775262369008682/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/51.404775262369008682/solutions/common/bizz/__init__.py", line 708, in _get_value
    azzert(step.step_id == name)
  File "/base/data/home/apps/e~rogerthat-server/51.404775262369008682/mcfw/properties.py", line 52, in azzert
    sorted(sys._getframe(1).f_locals.iteritems()), str(error_message) + '\n  Locals: '))
AssertionError: 
  Locals: 
  - name: message_remarks
  - step: <rogerthat.to.messaging.flow.FormFlowStepTO object at 0xf80d4990>
```

**Comment by bart-at-mobicage** [comment]
Sam manually created a new menu item with tag `__sln__.repair`
