### ISSUE TITLE
Signup is broken on IE10, IE11 and Edge

### ISSUE THREAD

**Issue by abom** [our-city-app/oca-backend#633]
On IE10, signup page is not rendered correctly.
Also, IE11 gave some client errors regarding grecaptcha

`grecaptcha is undefined
`

`Invalid ReCAPTCHA client id: undefined
`

`Cannot contact reCAPTCHA. Check your connection and try again.`

Related server error:

```
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/59.405053475098085593/mcfw/restapi.py", line 229, in post
    params = parse_parameters(f, parameters)
  File "/base/data/home/apps/e~rogerthat-server/59.405053475098085593/mcfw/rpc.py", line 187, in parse_parameters
    return get_parameters(parameters, kwarg_types)
  File "/base/data/home/apps/e~rogerthat-server/59.405053475098085593/mcfw/rpc.py", line 211, in get_parameters
    for name, type_ in kwarg_types.iteritems()}
  File "/base/data/home/apps/e~rogerthat-server/59.405053475098085593/mcfw/rpc.py", line 211, in <dictcomp>
    for name, type_ in kwarg_types.iteritems()}
  File "/base/data/home/apps/e~rogerthat-server/59.405053475098085593/mcfw/rpc.py", line 285, in parse_parameter
    return _parse_value(name, raw_type, value)
  File "/base/data/home/apps/e~rogerthat-server/59.405053475098085593/mcfw/rpc.py", line 403, in _parse_value
    raize()
  File "/base/data/home/apps/e~rogerthat-server/59.405053475098085593/mcfw/rpc.py", line 398, in raize
    % (name, type_, type(value), value))
ValueError: Incorrect type received for parameter 'city_customer_id'. Expected (<type 'int'>, <type 'long'>) and got <type 'NoneType'> (None).
```

**Comment by abom** [comment]
grecapcha errors were due to connection problems, trying to reproduce the server error on Winodws with IE11 but couldn't till now.

User agent

> Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko

**Comment by abom** [comment]
Client errors should be logged when this [pull request](https://github.com/our-city-app/oca-backend/pull/651) is merged, currently it gives 401.

**Comment by bart-at-mobicage** [comment]
Happened again this morning, so there should be a client_error. I didn't have time to search for it.

**Comment by abom** [comment]
Again, things work fine with the latest IE11, tried many times, the signup request is sent normally.

Another thing, we really need the ability to filter the client errors on platform version, as navigating through all platforms errors using Next/First buttons only are impossible.

**Comment by lucasvanhalst** [comment]
@abom I think we should look into sending the errors to stackdriver error reporting instead of our housemade 'client errors'. Only downside is that it's still in beta

**Comment by abom** [comment]
@lucasvanhalst A better way of course, the other option we have is to rewrite our homemade reporting of errors, it even duplicate the record for the same error.

**Comment by abom** [comment]
grecaptcha loading problem(on edge)

```
description: Caught exception in global scope: 'grecaptcha' is not defined

errorMessage: 'grecaptcha' is not defined
in https://dashboard.onzestadapp.be/static/js/solutions/sln-utils.js at line 179:9
signup@https://dashboard.onzestadapp.be/static/js/public/signup.js:211:13
   at x.event.dispatch (https://dashboard.onzestadapp.be/static/js/jquery-1.10.0.min.js:5:13803)
   at jQuery.event.dispatch (https://dashboard.onzestadapp.be/static/js/solutions/sln-utils.js:176:9)
   at v.handle (https://dashboard.onzestadapp.be/static/js/jquery-1.10.0.min.js:5:10607)

mobicageVersion: web

occurenceCount: 1

platform: 0

platformVersion: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299
```

**Comment by abom** [comment]
I got the same server error by mistake when trying to call the signupCallback without going throw the wizard (via calling grecaptcha.execute).

Despite i don't know how such thing can happen, but i hope the new way of loading grecaptcha prevents such behavior.

**Comment by abom** [comment]
Also, for IE10, even type Map is not supported, should we add an e.g. polyfill for such type or just we should only support IE11/Edge by now?

**Comment by bart-at-mobicage** [comment]
If it's not too much effort then I would support IE10 as well

**Comment by abom** [comment]
Used a normal object instead of Map as @lucasvanhalst suggested.
