### ISSUE TITLE
KeyError happened when deleting broadcast type

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#638]
```
12:22:03.766
[XX-OFFLOADv1] {"function":"/common/settings/broadcast/add_or_remove_type","request_data":{"broadcast_type":"Infosessies","delete":true},"success":false,"timestamp":1509358923,"response_data":"u'Infosessies'","type":"web","user":"f1fa03611669cf52935c883733287624"} (/base/data/home/apps/e~rogerthat-server/59.405053475098085593/rogerthat/utils/__init__.py:488)

12:22:03.766
u'Infosessies' (/base/data/home/apps/e~rogerthat-server/59.405053475098085593/add_1_monkey_patches.py:125)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/59.405053475098085593/mcfw/restapi.py", line 283, in run
    result = run(f, args, kwargs)
  File "/base/data/home/apps/e~rogerthat-server/59.405053475098085593/mcfw/rpc.py", line 180, in run
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/59.405053475098085593/mcfw/restapi.py", line 93, in wrapped
    return f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/59.405053475098085593/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/59.405053475098085593/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/59.405053475098085593/solutions/common/restapi/__init__.py", line 1866, in add_or_remove_broadcast_type
    if translated_broadcast_types[broadcast_type] in sln_settings.broadcast_types:
KeyError: u'Infosessies'
```

**Comment by abom** [comment]
tbh, i don't know how this error has occurred in the first place!
