### ISSUE TITLE
Failed to upload attachment when creating news item

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#649]
Request identity: service-e5d95a4d-a547-424e-904a-b8f969cd962a@rogerth.at - KINSHASA NEWS (slyongo via shop) (WEB)

```
KeyError: u'\u0301'
at quote (/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib.py:1294)
at _quote_filename (/base/data/home/apps/e~rogerthat-server/63.405326633714776717/lib/cloudstorage/api_utils.py:94)
at open (/base/data/home/apps/e~rogerthat-server/63.405326633714776717/lib/cloudstorage/cloudstorage_api.py:91)
at upload_to_gcs (/base/data/home/apps/e~rogerthat-server/63.405326633714776717/rogerthat/bizz/gcs.py:37)
at post (/base/data/home/apps/e~rogerthat-server/63.405326633714776717/solutions/common/handlers/broadcast.py:58)
```

**Comment by bart-at-mobicage** [comment]
Another occurrence

```
2018-04-26 21:49:26.611 CEST
u'\xe9' (/base/data/home/apps/e~rogerthat-server/20180424t113917.409246710421677010/add_1_monkey_patches.py:127)
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180424t113917.409246710421677010/solutions/common/handlers/loyalty.py", line 103, in post
    upload_to_gcs(uploaded_file.value, content_type, gcs_filename)
  File "/base/data/home/apps/e~rogerthat-server/20180424t113917.409246710421677010/rogerthat/bizz/gcs.py", line 38, in upload_to_gcs
    with cloudstorage.open(file_name, 'w', content_type=content_type) as f:
  File "/base/data/home/apps/e~rogerthat-server/20180424t113917.409246710421677010/lib/cloudstorage/cloudstorage_api.py", line 91, in open
    filename = api_utils._quote_filename(filename)
  File "/base/data/home/apps/e~rogerthat-server/20180424t113917.409246710421677010/lib/cloudstorage/api_utils.py", line 94, in _quote_filename
    return urllib.quote(filename)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_dist/lib/python2.7/urllib.py", line 1294, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xe9'
```
