### ISSUE TITLE
Import menu from excel should not allow unknown units or items without price

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#666]
- [x] Don't allow unknown units when importing

![screen shot 2017-11-20 at 13 15 58](https://user-images.githubusercontent.com/17762105/33018022-f7f9cd94-cdf4-11e7-941b-a9ffac9a5a16.png)

```
Failure in common_provision (/base/data/home/apps/e~rogerthat-server/67.405587551156698020/add_1_monkey_patches.py:125)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/solutions/common/bizz/__init__.py", line 608, in common_provision
    needs_reload = bizz.provision(service_user, friends)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/solutions/flex/bizz.py", line 131, in provision
    main_branding, default_lang)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/add_1_monkey_patches.py", line 235, in _allow_transaction_propagation
    return func(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/rogerthat/utils/transactions.py", line 103, in run_in_xg_transaction
    return db.run_in_transaction_options(xg_on, function, *args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/add_1_monkey_patches.py", line 211, in wrapped
    r = run(transaction_guid)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/add_1_monkey_patches.py", line 193, in run
    return _orig_run_in_transaction_options(options, *args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2647, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2667, in _DoOneTry
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/solutions/common/bizz/provisioning.py", line 740, in provision_all_modules
    POKE_TAGS[module])
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/solutions/common/bizz/provisioning.py", line 1454, in put_order
    static_flow_hash = _put_advanced_order_flow(sln_settings, sln_order_settings, main_branding, default_lang)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/solutions/common/bizz/provisioning.py", line 1388, in _put_advanced_order_flow
    item.unit_str = solutions.translate_unit_symbol(lang, item.unit)
  File "/base/data/home/apps/e~rogerthat-server/67.405587551156698020/solutions/__init__.py", line 81, in translate_unit_symbol
    return translate(language, SOLUTION_COMMON, UNIT_SYMBOLS[unit])
KeyError: None
```

- [x] Also prevent the following error when importing:

> MessageFlowDesignValidationException: 40008 - Message flow design is not valid: {&apos;reason&apos;: u&quot;Unit price is a required argument in item with id &apos;784233df-1a20-44be-a595-ba6694258bd3&apos; for category with id &apos;08b401e7-d54e-4ed0-b66c-4c4322653ef3&apos;&quot;, &apos;property&apos;: &apos;unit_price&apos;} - Invalid value For Advanced order 'message_advanced_order' - {'validation_error': u"{&apos;reason&apos;: u&quot;Unit price is a required argument in item with id &apos;784233df-1a20-44be-a595-ba6694258bd3&apos; for category with id &apos;08b401e7-d54e-4ed0-b66c-4c4322653ef3&apos;&quot;, &apos;property&apos;: &apos;unit_price&apos;} - Invalid value For Advanced order 'message_advanced_order'"}

**Comment by abom** [comment]
I see the **€** sign also in the **price** field, I suggest we tell the user he should the menu to see an example of the correct format.

**Comment by bart-at-mobicage** [comment]
This was the row without a price (0 EUR)
![screen shot 2017-11-20 at 13 35 24](https://user-images.githubusercontent.com/17762105/33018694-b9e62784-cdf7-11e7-8f5f-8cc82ff7877c.png)

**Comment by bart-at-mobicage** [comment]
Summary:
- Only known units are allowed
- When the price is empty or 0, publishing doesn't give an error anymore
