### ISSUE TITLE
Catch FriendNotFoundException when accepting loyalty user data

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/oca-backend#710]
```
Permanent failure attempting to execute task (/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/add_1_monkey_patches.py:127)
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/add_1_monkey_patches.py", line 327, in _new_deferred_run
    return func(*args, **kwds)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/solutions/common/bizz/loyalty.py", line 249, in update_user_data_user_loyalty
    system.put_user_data(email, json.dumps(user_data), service_identity, app_id)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/rogerthat/rpc/service.py", line 366, in wrapped
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/rogerthat/service/api/system.py", line 322, in put_user_data
    set_user_data(service_identity_user, create_app_user(users.User(email), app_id), user_data)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/rogerthat/bizz/service/__init__.py", line 2610, in set_user_data
    set_user_data_object(service_identity_user, friend_user, data_dict, replace, must_be_friends)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/rogerthat/bizz/service/__init__.py", line 2715, in set_user_data_object
    run_in_xg_transaction(trans, data_dict)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/rogerthat/utils/transactions.py", line 103, in run_in_xg_transaction
    return db.run_in_transaction_options(xg_on, function, *args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/add_1_monkey_patches.py", line 217, in wrapped
    r = run(transaction_guid)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/add_1_monkey_patches.py", line 197, in run
    return _orig_run_in_transaction_options(options, *args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/1/google/appengine/api/datastore.py", line 2647, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/1/google/appengine/api/datastore.py", line 2667, in _DoOneTry
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/rogerthat/bizz/service/__init__.py", line 2631, in trans
    raise FriendNotFoundException()
FriendNotFoundException: 60011 - User not in friends list - {}
```

**Comment by bart-at-mobicage** [comment]
https://github.com/rogerthat-platform/rogerthat-backend/issues/370
