### ISSUE TITLE
Invalid broadcast type when sending sandwich message

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/oca-backend#711]
Investigate if the broadcast types for sandwiches are properly removed when removing the module from a service 

```
Permanent failure attempting to execute task (/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/add_1_monkey_patches.py:127)
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/add_1_monkey_patches.py", line 327, in _new_deferred_run
    return func(*args, **kwds)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/solutions/common/cron/sandwich.py", line 134, in _broadcast
    alert_flags, timeout=timeout)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/rogerthat/rpc/service.py", line 366, in wrapped
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/rogerthat/service/api/messaging.py", line 154, in broadcast
    validate_broadcast_type(service_user, broadcast_type)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20171228t160836.406538483996163887/rogerthat/bizz/service/__init__.py", line 2991, in validate_broadcast_type
    raise InvalidBroadcastTypeException(broadcast_type)
InvalidBroadcastTypeException: 60005 - Invalid broadcast type - {'broadcast_type': u'Broodjes op zaterdag'}
```

**Comment by bart-at-mobicage** [comment]
Occurs often.

I think it happens when configuring the reminders, but not publishing the changes. So don't send the broadcast message if the broadcast types aren't published yet.
