### ISSUE TITLE
OSA Terminal showing "Unknown exception occurred" on startup

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#727]
La Tapa Canaria reported this issue

**Comment by RubenMattan** [comment]
There was an issue with user data being 'None'
Bart already deployed a fix and now where investigating if all user/service data on the clients is ok.

Fix: https://github.com/rogerthat-platform/rogerthat-backend/commit/90990995d173379ca610799aa8829fda272e1087

**Comment by RubenMattan** [comment]
Sometimes the update of service data fails because of the following error, why this happens is unclear yet.

```python
function: defer_send_app_data_from_db


ERROR    2018-01-08 14:41:31,464 add_1_monkey_patches.py:127] Permanent failure attempting to execute task

Traceback (most recent call last):
  File "/Users/ruben/google-cloud-sdk/platform/google_appengine/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/Users/ruben/google-cloud-sdk/platform/google_appengine/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/Users/ruben/mobicage/git/oca-backend/build/add_1_monkey_patches.py", line 327, in _new_deferred_run
    return func(*args, **kwds)
  File "/Users/ruben/google-cloud-sdk/platform/google_appengine/google/appengine/ext/deferred/deferred.py", line 178, in run_from_datastore
    raise PermanentTaskFailure()
PermanentTaskFailure
```

**Comment by RubenMattan** [comment]
Other fix: https://github.com/rogerthat-platform/rogerthat-backend/pull/377/commits/b38d1542cc387d233d91b15819358683bd7d5158

**Comment by bart-at-mobicage** [comment]
This was a tablet where osa-launcher was removed, but the "OSA Loyalty" app was still there. It was never updated. It had build version around 1500, probably `updateUserData` was implemented yet.

We removed "OSA Loyalty" and installed "OSA Terminal" from the Play Store.
