### ISSUE TITLE
Error in pharmacy order

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#734]
The step id was message_message_photo_upload_prescription in the past, but was renamed to message_photo_upload_prescription. All service with pharmacy_order module were provisioned again. So I dont understand why the step id is still message_message_photo_upload_prescription. Maybe we should do something like `picture_url = _get_value(steps[1], steps[1].id)` instead of `picture_url = _get_value(steps[1], u'message_photo_upload_prescription')`

```
Starting in new context: flex.messaging.flow_member_result (/base/data/home/apps/e~rogerthat-server/20180110t204419.406844404764512608/rogerthat/rpc/service.py:222)
{"callback_name":null,"params":{"end_id":null,"service_identity":"+default+","end_message_flow_id":null,"message_flow_run_id":"_js_c52d9097-ba01-65c3-dbb5-766cf313162","member":"***@gmail.com","parent_message_key":"_js_c27b7623-6239-384d-9510-c212208c5b36","tag":"__sln__.pharmacy_order","steps":[{"received_timestamp":1515672903,"message_flow_id":"ahNkZXZ-bW9iaWNhZ2VjbG91ZGhycj8LEgptYy10cmFja2VyIgpzMUBnc20uZ3NtDAsSEU1lc3NhZ2VGbG93RGVzaWduIg5waGFybWFjeV9vcmRlcgw","button":"Ja","step_type":"message_step","step_id":"message_has_prescription","message":"Heeft u een voorschrift?","acknowledged_timestamp":1515672904,"answer_id":"button_button_yes"},{"received_timestamp":1515672905,"message_flow_id":"ahNkZXZ-bW9iaWNhZ2VjbG91ZGhycj8LEgptYy10cmFja2VyIgpzMUBnc20uZ3NtDAsSEU1lc3NhZ2VGbG93RGVzaWduIg5waGFybWFjeV9vcmRlcgw","button":"Volgende","step_type":"form_step","form_result":{"type":"unicode_result","result":{"value":"https://rogerth.at/unauthenticated/mobi/service/photo/download/***"}},"form_type":"photo_upload","step_id":"message_message_photo_upload_prescription","message":"Maak een foto van uw voorschrift.","acknowledged_timestamp":1515672939,"display_value":"https://rogerth.at/unauthenticated/mobi/service/photo/download/***","answer_id":"positive"},{"received_timestamp":1515672940,"message_flow_id":"ahNkZXZ-bW9iaWNhZ2VjbG91ZGhycj8LEgptYy10cmFja2VyIgpzMUBnc20uZ3NtDAsSEU1lc3NhZ2VGbG93RGVzaWduIg5waGFybWFjeV9vcmRlcgw","button":"Versturen","step_type":"form_step","form_result":{"type":"unicode_result","result":{"value":""}},"form_type":"text_block","step_id":"message_message_remarks_box","message":"Heeft u opmerkingen en/of vragen?","acknowledged_timestamp":1515672943,"display_value":"","answer_id":"positive"}],"flush_message_flow_id":"ahNkZXZ-bW9iaWNhZ2VjbG91ZGhycj8LEgptYy10cmFja2VyIgpzMUBnc20uZ3NtDAsSEU1lc3NhZ2VGbG93RGVzaWduIg5waGFybWFjeV9vcmRlcgw","user_details":[{"public_key":null,"name":"*** at gmail.com","language":"nl_BE","app_id":"be-loc","avatar_url":"https://rogerth.at/unauthenticated/mobi/cached/avatar/5907930188611584","public_keys":[],"email":"***@gmail.com"}],"result_key":"146affee-4695-437b-b740-d783729644d8","flow_params":null,"flush_id":"flush_flush"},"method":"messaging.flow_member_result","id":"259e1f14-f6c9-11e7-b3d6-db548bc337bd"}
```

```
Caught exception in handle_solution_api_callback: flex.64 (/base/data/home/apps/e~rogerthat-server/20180110t204419.406844404764512608/add_1_monkey_patches.py:127)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/20180110t204419.406844404764512608/rogerthat/rpc/solutions.py", line 71, in handle_solution_api_callback
    return f(service_user, **effective_kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180110t204419.406844404764512608/rogerthat/rpc/solutions.py", line 34, in wrapped
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180110t204419.406844404764512608/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180110t204419.406844404764512608/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180110t204419.406844404764512608/solutions/common/api_callback_handlers.py", line 120, in common_messaging_flow_member_result
    flush_message_flow_id, service_identity, user_details)
  File "/base/data/home/apps/e~rogerthat-server/20180110t204419.406844404764512608/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180110t204419.406844404764512608/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180110t204419.406844404764512608/solutions/common/bizz/pharmacy/order.py", line 63, in pharmacy_order_received
    picture_url = _get_value(steps[1], u'message_photo_upload_prescription')
  File "/base/data/home/apps/e~rogerthat-server/20180110t204419.406844404764512608/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180110t204419.406844404764512608/solutions/common/bizz/__init__.py", line 719, in _get_value
    azzert(step.step_id == name)
  File "/base/data/home/apps/e~rogerthat-server/20180110t204419.406844404764512608/mcfw/properties.py", line 52, in azzert
    sorted(sys._getframe(1).f_locals.iteritems()), str(error_message) + '\n  Locals: '))
AssertionError: 
  Locals: 
  - name: message_photo_upload_prescription
  - step: <rogerthat.to.messaging.flow.FormFlowStepTO object at 0xf6035dd0>
```

```
Caught exception while executing start_in_new_context callback function (/base/data/home/apps/e~rogerthat-server/20180110t204419.406844404764512608/add_1_monkey_patches.py:127)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/20180110t204419.406844404764512608/rogerthat/rpc/rpc.py", line 327, in finalize
    err_func(exception)
  File "/base/data/home/apps/e~rogerthat-server/20180110t204419.406844404764512608/rogerthat/rpc/service.py", line 200, in process_error
    json.dumps(call_dict), json.dumps(dict(id=call_dict['id'], result=None, error=error)),
  File "/base/data/home/apps/e~rogerthat-server/20180110t204419.406844404764512608/add_1_monkey_patches.py", line 257, in _new_json_dumps
    return _orig_json_dumps(*args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_dist/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_dist/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_dist/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_dist/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: AssertionError('\n  Locals: \n  - name: message_photo_upload_prescription\n  - step: <rogerthat.to.messaging.flow.FormFlowStepTO object at 0xf6035dd0>',) is not JSON serializable
```

**Comment by abom** [comment]
Tried to find any logs related to problems when provisioning/publishing, but couldn't.
