### ISSUE TITLE
Failed to process sandwich order

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#77]
```python
Queue: default
deferred.run(solutions.common.bizz.sandwich.process_sandwich_order,
             users.User(email='service-7a9e4fd8-acb9-426f-8fe3-f3c505b168e4@rogerth.at'),
             u'+default+',
             [<rogerthat.to.service.UserDetailsTO object at 0xf92f9cd0>],
             u'type_5144752345317376',
             None,
             None,
             u'',
             None,
             u'e0d8d550-f97d-45ee-8037-097401c45d87')
```

```python
'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 310, in post
    self.run_from_request()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 305, in run_from_request
    run(self.request.body)
  File "/base/data/home/apps/s~mobicagecloudhr/1.396953457445168400/add_1_monkey_patches.py", line 270, in _new_deferred_run
    return func(*args, **kwds)
  File "/base/data/home/apps/s~mobicagecloudhr/1.396953457445168400/solutions/common/bizz/sandwich.py", line 99, in process_sandwich_order
    topping_id = int(topping.split('_')[-1])
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by lucasvanhalst** [comment]
Was already fixed but not yet deployed
