### ISSUE TITLE
BusinessException concerning broadcast types while publishing

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#770]
No idea what happens. But one service that had this issue could not send news afterwards. They got the error message _"Invalid broadcast type (if you added a new broadcast type, please publish the changes first)."_ afterwards.

```
...

2018-03-05 13:28:55.326 CET
Finalizing transaction items (6 left) ... (/base/data/home/apps/e~rogerthat-server/20180301t140453.407997609724218242/rogerthat/utils/transactions.py:55)

2018-03-05 13:28:55.326 CET
Executing post-transaction action: put_menu_item (/base/data/home/apps/e~rogerthat-server/20180301t140453.407997609724218242/rogerthat/utils/transactions.py:58)

2018-03-05 13:28:55.738 CET
[XX-OFFLOADv1]{"function":"system.put_menu_item","status":false,"request_data":{"icon_color":null,"static_flow":null,"label":"Notificatie instellingen","is_broadcast_settings":true,"icon_name":"fa-bell","tag":"__rt__.broadcast_settings","coords":[3,2,0],"roles":[],"broadcast_branding":"7EB32792D5E6F4A8FDE0095B015B3561A7BB294DC78B9CA53B8901B7328736D1","action":0,"requires_wifi":false,"screen_branding":null,"link":null,"run_in_background":true},"timestamp":1520252935.73838,"response_data":{"error":{"message":"*****","code":1000}},"type":"api","user":"service-***-3f1febc2de62@rogerth.at"} (/base/data/home/apps/e~rogerthat-server/20180301t140453.407997609724218242/lib/log_offload/log_offload.py:58)

2018-03-05 13:28:55.741 CET
Caught exception in transaction_done_callback (/base/data/home/apps/e~rogerthat-server/20180301t140453.407997609724218242/add_1_monkey_patches.py:127)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/20180301t140453.407997609724218242/rogerthat/utils/transactions.py", line 59, in finalize
    callback_func(*callback_args, **callback_kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180301t140453.407997609724218242/rogerthat/rpc/service.py", line 385, in wrapped
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180301t140453.407997609724218242/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180301t140453.407997609724218242/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180301t140453.407997609724218242/rogerthat/service/api/system.py", line 272, in put_menu_item
    broadcast_branding, action, link, fall_through)
  File "/base/data/home/apps/e~rogerthat-server/20180301t140453.407997609724218242/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180301t140453.407997609724218242/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180301t140453.407997609724218242/rogerthat/bizz/service/__init__.py", line 1945, in create_menu_item
    run_in_xg_transaction(trans, screen_branding)
  File "/base/data/home/apps/e~rogerthat-server/20180301t140453.407997609724218242/rogerthat/utils/transactions.py", line 103, in run_in_xg_transaction
    return db.run_in_transaction_options(xg_on, function, *args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180301t140453.407997609724218242/add_1_monkey_patches.py", line 217, in wrapped
    r = run(transaction_guid)
  File "/base/data/home/apps/e~rogerthat-server/20180301t140453.407997609724218242/add_1_monkey_patches.py", line 197, in run
    return _orig_run_in_transaction_options(options, *args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/api/datastore.py", line 2647, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/api/datastore.py", line 2667, in _DoOneTry
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180301t140453.407997609724218242/rogerthat/bizz/service/__init__.py", line 1936, in trans
    u"You can not create a broadcast settings menu item if there are no broadcast types. You can add new broadcast types at Broadcast center.")
  File "/base/data/home/apps/e~rogerthat-server/20180301t140453.407997609724218242/rogerthat/utils/__init__.py", line 404, in bizz_check
    raise error_class(error_message)
BusinessException: You can not create a broadcast settings menu item if there are no broadcast types. You can add new broadcast types at Broadcast center.
```

**Comment by lucasvanhalst** [comment]
Can't reproduce this, an error message is shown before publish is started if there are no broadcast types
Perhaps they removed all broadcast types immediately after starting publishing? But even then I can't reproduce it

**Comment by abom** [comment]
I reproduced the error only with newly create services.
As @lucasvanhalst said, it appears before publish is started.

In provisioning.put_broadcast, system.put_broadcast_types does not set broadcast types.

**Comment by bart-at-mobicage** [comment]
is it because the service_profile is modified inside the uber transaction and later, in the same transaction, being fetched again?

**Comment by bart-at-mobicage** [comment]
Lot's of occurrences recently :/
