### ISSUE TITLE
Couldn't build NewsItemTO

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#782]
```
2018-03-08 14:24:22.781 CET
[XX-OFFLOADv1]{"function":"news.list","status":false,"request_data":{"cursor":null,"service_identity":null,"batch_count":5},"timestamp":1520515462.7815001,"response_data":{"error":{"message":"*****","code":1000}},"type":"api","user":"service-52130bd6-e4e9-4d04-a371-f85aa5bded3e@rogerth.at"} (/base/data/home/apps/e~rogerthat-server/20180308t141532.408160135586865355/lib/log_offload/log_offload.py:58)

2018-03-08 14:24:22.784 CET
Not all items are from expected type <type 'unicode'>! Encountered item at index 0 with type <class 'google.appengine.api.users.User'>. (/base/data/home/apps/e~rogerthat-server/20180308t141532.408160135586865355/add_1_monkey_patches.py:127)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/20180308t141532.408160135586865355/mcfw/restapi.py", line 283, in run
    result = run(f, args, kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180308t141532.408160135586865355/mcfw/rpc.py", line 180, in run
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180308t141532.408160135586865355/mcfw/restapi.py", line 93, in wrapped
    return f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180308t141532.408160135586865355/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180308t141532.408160135586865355/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180308t141532.408160135586865355/solutions/common/restapi/news.py", line 45, in rest_get_news
    return get_news(cursor, service_identity)
  File "/base/data/home/apps/e~rogerthat-server/20180308t141532.408160135586865355/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180308t141532.408160135586865355/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180308t141532.408160135586865355/solutions/common/bizz/news.py", line 66, in get_news
    news_list = news.list_news(cursor, 5, service_identity)
  File "/base/data/home/apps/e~rogerthat-server/20180308t141532.408160135586865355/rogerthat/rpc/service.py", line 385, in wrapped
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180308t141532.408160135586865355/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180308t141532.408160135586865355/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180308t141532.408160135586865355/rogerthat/service/api/news.py", line 86, in list_news
    return news.get_news_by_service(cursor, batch_count, service_identity_user, updated_since)
  File "/base/data/home/apps/e~rogerthat-server/20180308t141532.408160135586865355/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180308t141532.408160135586865355/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180308t141532.408160135586865355/rogerthat/bizz/news.py", line 183, in get_news_by_service
    return NewsItemListResultTO(news_items, u'%s' % qry.cursor(), base_url, False)
  File "/base/data/home/apps/e~rogerthat-server/20180308t141532.408160135586865355/rogerthat/to/news.py", line 521, in __init__
    self.result = [NewsItemTO.from_model(news_item, base_url, include_statistics) for news_item in news_items]
  File "/base/data/home/apps/e~rogerthat-server/20180308t141532.408160135586865355/rogerthat/to/news.py", line 419, in from_model
    model.published, statistics, model.action_count, model.follow_count, target_audience, model.role_ids)
  File "/base/data/home/apps/e~rogerthat-server/20180308t141532.408160135586865355/rogerthat/to/news.py", line 364, in __init__
    qr_code_content, qr_code_caption, version, timestamp, flags, news_type)
  File "/base/data/home/apps/e~rogerthat-server/20180308t141532.408160135586865355/rogerthat/to/news.py", line 241, in __init__
    self.users_that_rogered = users_that_rogered
  File "/base/data/home/apps/e~rogerthat-server/20180308t141532.408160135586865355/mcfw/properties.py", line 122, in __set__
    "type %s." % (unicode(self.type), i, type(x)))
ValueError: Not all items are from expected type <type 'unicode'>! Encountered item at index 0 with type <class 'google.appengine.api.users.User'>.
```

**Comment by RubenMattan** [comment]
already fixed
