### ISSUE TITLE
Couldn't publish due to bad xml in order flow

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#860]
![image](https://user-images.githubusercontent.com/17762105/39113733-e7ce708a-46dc-11e8-9b82-acd0a054d4a0.png)

`service-6394b887-cf57-4fc2-9089-27b1974e2d78@rogerth.at`

```
2018-04-22 11:24:26.642 CEST Creating ORDER message flow

2018-04-22 11:24:27.081 CEST Could not parse XML:
<?xml version="1.0" encoding="utf-8"?>
<messageFlowDefinitionSet xmlns="https://rogerth.at/api/1/MessageFlow.xsd">
    <definition name="order"
                language="nl"
                startReference="flowcode_check_feature_advanced_order">
        <end id="end_advanced_order"
             waitForFollowUpMessage="false"/>
        <end id="end_processing"
             waitForFollowUpMessage="false"/>
        <end id="end_feature_not_supported"
                 waitForFollowUpMessage="false" />

        <flowCode
            id="flowcode_check_feature_advanced_order"
            exceptionReference="message_feature_not_supported">
            <outlet
                reference="message_advanced_order"
                name="message_advanced_order"
                value="message_advanced_order" />
            
            <outlet
                reference="message_feature_not_supported"
                name="not_supported"
                value="not_supported" />
            <javascriptCode>
                var notSupported = function() {
                    return { outlet: &quot;not_supported&quot; };
                };
                function run(rogerthat, mfr){
                    if (!rogerthat.system || !rogerthat.system.appVersion) {
                        return notSupported();
                    }
                    var appVersion = rogerthat.system.appVersion.split(&quot;.&quot;).map(function(x) {
                        return parseInt(x);
                    });
    
                    if (rogerthat.system.os == &quot;android&quot;) {
                        if (!(appVersion[0] &gt; 1
                                || appVersion[1] &gt; 0
                                || appVersion[2] &gt;= 1626)) {
                            return notSupported();
                        }
                    } else if (rogerthat.system.os == &quot;ios&quot;) {
                        if (!(appVersion[0] &gt; 1
                            || appVersion[1] &gt; 0
                            || appVersion[2] &gt;= 765)) {
                            return notSupported();
                        }
                    }
                    
                    var outlet = 'message_advanced_order';
                    
                    return {outlet: outlet, defaultValue: mfr.flow_params.advancedOrder };
                }
            </javascriptCode>
        </flowCode>

        <message
            brandingKey="4EAEFC354D70CFE703E9A9B26C262B6475A2A90E2FBD1B13724F3C3B50A4AB69"
            id="message_feature_not_supported"
            alertIntervalType="NONE"
            alertType="SILENT"
            allowDismiss="true"
            dismissReference="end_feature_not_supported"
            vibrate="false"
            autoLock="true">
            <content>Deze functionaliteit is niet beschikbaar in uw versie van de app. Gelieve AppStore of Google Play te openen en de app te updaten.</content>
        </message>

        <formMessage id="message_advanced_order"
                     alertIntervalType="NONE"
                     alertType="SILENT"
                     brandingKey="4EAEFC354D70CFE703E9A9B26C262B6475A2A90E2FBD1B13724F3C3B50A4AB69"
                     positiveReference="message_comment"
                     vibrate="false"
                     autoLock="true"
                     negativeReference="end_advanced_order">
            <content>Selecteer hetgeen u wil bestellen

Minimum 30 minuten voor afhalen bestellen</content>
            <form positiveButtonConfirmation=""
                  negativeButtonCaption="Annuleren"
                  positiveButtonCaption="Volgende"
                  negativeButtonConfirmation="">
                <widget xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:type="AdvancedOrderWidget"
                        currency="€"
                        leapTime="1800">
                    
                    
                    <category id="640d8bbc-8a42-58d9-d29f-f8fcd7a732b8">
                        <name>gezond ontbijt</name>
                        
                            
                                <item id="f43bcc77-e37d-7db0-c1cf-7ad68f1ea940"
                                  value="0"
                                  unitPrice="0"
                                  hasPrice="false"
                                  step="1"
                                  
                                  unit="st."
                                  
                                  
                                  imageUrl="https://rogerth.at/solutions/common/public/menu/image/6019927119495168"
                                  
                                >
                                    <name>gezond ontbijt</name>
                                    <description>indien u geïnteresseerd bent in een gezonde manier van ontbijten kan u ons altijd contacteren voor meer info!</description>
                                </item>
                            
                        
                    </category>
                    
                    
                </widget>
            </form>
        </formMessage>

        
        
        <flowCode
                id="flow_code_phone_default"
                exceptionReference="message_phone">
            <outlet
                    reference="message_phone"
                    name="message_phone"
                    value="message_phone"/>
            <javascriptCode>
                function run(rogerthat, messageFlowRun) {
                    return { outlet: 'message_phone', defaultValue: rogerthat.user.data.phone };
                };
            </javascriptCode>
        </flowCode>

        <formMessage id="message_phone"
                     alertIntervalType="NONE"
                     alertType="SILENT"
                     brandingKey="4EAEFC354D70CFE703E9A9B26C262B6475A2A90E2FBD1B13724F3C3B50A4AB69"
                     positiveReference="flowcode_set_datetime_step"
                     vibrate="false"
                     autoLock="true"
                     negativeReference="end_advanced_order">
            <content>Geef uw telefoonnummer in.</content>
            <form positiveButtonConfirmation=""
                  negativeButtonCaption="Annuleren"
                  positiveButtonCaption="Volgende"
                  negativeButtonConfirmation="" >
                <widget xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:type="TextLineWidget"
                        keyboardType="PHONE"
                        maxChars="50"/>

                <javascriptValidation>
                    function run(result){
                        if (!result.value || result.value.length &lt; 8) {
                            return "Gelieve een geldig telefoonnummer in te vullen.";
                        }
                     }
                </javascriptValidation>
            </form>
        </formMessage>
        <formMessage id="message_comment"
                     brandingKey="4EAEFC354D70CFE703E9A9B26C262B6475A2A90E2FBD1B13724F3C3B50A4AB69"
                     alertIntervalType="NONE"
                     alertType="SILENT"
                     positiveReference="flow_code_phone_default"
                     vibrate="false"
                     autoLock="true"
                     negativeReference="flow_code_phone_default">
            <content>Voeg producten toe die niet beschikbaar waren in de catalogus en/of voeg commentaar toe.</content>
            <form positiveButtonConfirmation=""
                  negativeButtonCaption="Overslaan"
                  positiveButtonCaption="Volgende"
                  negativeButtonConfirmation="">
                <widget xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:type="TextBlockWidget"
                        maxChars="1000"
                        placeholder=""
                        value=""/>
            </form>
        </formMessage>
        <formMessage brandingKey="4EAEFC354D70CFE703E9A9B26C262B6475A2A90E2FBD1B13724F3C3B50A4AB69"
                     id="message_takeaway_time"
                     alertIntervalType="NONE" alertType="SILENT"
                     positiveReference="flow_code_check_internet_before_flush"
                     vibrate="false" autoLock="true"
                     negativeReference="end_advanced_order">
            <content>Selecteer een datum en tijd om uw bestelling af te halen.</content>
            <form positiveButtonCaption="Verzenden"
                  negativeButtonCaption="Annuleren" >
                <widget xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:type="SelectDateWidget"
                        minuteInterval="15"
                        mode="date_time"
                        unit="&lt;value/&gt;"
                        />

                <javascriptValidation>
                    function run(result, rogerthat){
                        
                        var holidayDates = [{&quot;to&quot;:1532901599,&quot;from&quot;:1531432800}];
                        function isInHoliday(){
                            for(var i = 0; i &lt; holidayDates.length; i ++){
                                if(holidayDates[i].from &lt;= selectedDateTime &amp;&amp; selectedDateTime &lt; holidayDates[i].to){
                                    return true;
                                }
                            }
                            return false;
                        }
                        function isInWorkingHours(){
                            var selectedDate = new Date(selectedDateTime * 1000);
                            var dayToday = selectedDate.getUTCDay();
                            var sAfterMidnight = selectedDateTime % 86400;
                            var canOrder = orderableTimes.filter(function(t) {
                                return dayToday === t.day &amp;&amp; (t.time_until &gt;= sAfterMidnight &amp;&amp; sAfterMidnight &gt;= t.time_from);
                            });
                            return !!canOrder.length;
                        }
                        var orderableTimes = [{&quot;time_from&quot;:57600,&quot;time_until&quot;:79200,&quot;day&quot;:1},{&quot;time_from&quot;:57600,&quot;time_until&quot;:79200,&quot;day&quot;:2},{&quot;time_from&quot;:57600,&quot;time_until&quot;:79200,&quot;day&quot;:3},{&quot;time_from&quot;:57600,&quot;time_until&quot;:79200,&quot;day&quot;:4},{&quot;time_from&quot;:57600,&quot;time_until&quot;:79200,&quot;day&quot;:5},{&quot;time_from&quot;:32400,&quot;time_until&quot;:64800,&quot;day&quot;:6}];
                        var leapTime = 1800;

                        var timezoneOffsets = [[1524389066,1540688400,7200],[1540688400,1553994000,3600],[1553994000,1572138000,7200],[1572138000,1585443600,3600],[1585443600,1603587600,7200],[1603587600,1616893200,3600],[1616893200,1635642000,7200],[1635642000,1648342800,3600],[1648342800,1667091600,7200],[1667091600,1679792400,3600],[1679792400,1698541200,7200],[1698541200,1711846800,3600],[1711846800,1729990800,7200],[1729990800,1743296400,3600],[1743296400,1761440400,7200],[1761440400,1774746000,3600],[1774746000,1792890000,7200],[1792890000,1806195600,3600],[1806195600,1824944400,7200],[1824944400,1837645200,3600]];
                        var currentDateTimeSeconds = new Date().getTime() / 1000;
                        var timezoneOffset = 0;
                        for (var i=0; i &lt; timezoneOffsets.length; i ++) {
                            var zone = timezoneOffsets[i];
                            if (zone[0] &lt; currentDateTimeSeconds &amp;&amp; currentDateTimeSeconds &lt;= zone[1]) {
                                timezoneOffset = zone[2];
                                break;
                            }
                        }
                        var selectedDateTime = result.value;
                        if(isInHoliday()){
                            var holidayDatesStr = [&quot;13 jul. 2018 tot 29 jul. 2018&quot;];;
                            var holidayStr = '';
                            for(var i = 0; i &lt; holidayDatesStr.length; i ++){
                                holidayStr += holidayDatesStr[i];
                            }
                            return 'U kan op het geselecteerde moment geen bestelling afhalen omdat we dan met verlof zijn. We zijn met verlof tijdens deze periodes:\n' + holidayStr;
                        }
                        else if (selectedDateTime &lt; (currentDateTimeSeconds + leapTime + timezoneOffset)){ /* no idea why timezone has to be added here but it works */
                            return 'Uw gekozen afhaalmoment is te kortbij. Uw afhaalmoment moet minimum 30 minuten na het doorgeven van uw bestelling zijn.';
                        }else if(isInWorkingHours()){
                            return;
                        }
                        else{
                            return 'Het afhaalmoment moet tijdens de openingsuren zijn. U kan een bestelling plaatsen tijdens deze periodes: \nMaandag tussen 16:00 en 22:00\nDinsdag tussen 16:00 en 22:00\nWoensdag tussen 16:00 en 22:00\nDonderdag tussen 16:00 en 22:00\nVrijdag tussen 16:00 en 22:00\nZaterdag tussen 09:00 en 18:00';
                        }
                    }
                </javascriptValidation>
            </form>
        </formMessage>
        <flowCode
                id="flowcode_set_datetime_step"
                exceptionReference="message_takeaway_time">
            <outlet
                    reference="message_takeaway_time"
                    name="message_takeaway_time"
                    value="message_takeaway_time" />
            <javascriptCode>
                function run(rogerthat, messageFlowRun){
                    var phoneNumber = messageFlowRun.steps[messageFlowRun.steps.length -1].form_result.result.value;
                    if (phoneNumber !== rogerthat.user.data.phone) {
                        rogerthat.user.data.phone = phoneNumber;
                        rogerthat.user.put();
                    }
                    var holidayDates = rogerthat.service.data.settings.holidays.dates;
                    var orderableTimes = [{&quot;time_from&quot;:57600,&quot;time_until&quot;:79200,&quot;day&quot;:1},{&quot;time_from&quot;:57600,&quot;time_until&quot;:79200,&quot;day&quot;:2},{&quot;time_from&quot;:57600,&quot;time_until&quot;:79200,&quot;day&quot;:3},{&quot;time_from&quot;:57600,&quot;time_until&quot;:79200,&quot;day&quot;:4},{&quot;time_from&quot;:57600,&quot;time_until&quot;:79200,&quot;day&quot;:5},{&quot;time_from&quot;:32400,&quot;time_until&quot;:64800,&quot;day&quot;:6}];
                    var leapTime = 1800;

                    var timezoneOffsets = [[1524389066,1540688400,7200],[1540688400,1553994000,3600],[1553994000,1572138000,7200],[1572138000,1585443600,3600],[1585443600,1603587600,7200],[1603587600,1616893200,3600],[1616893200,1635642000,7200],[1635642000,1648342800,3600],[1648342800,1667091600,7200],[1667091600,1679792400,3600],[1679792400,1698541200,7200],[1698541200,1711846800,3600],[1711846800,1729990800,7200],[1729990800,1743296400,3600],[1743296400,1761440400,7200],[1761440400,1774746000,3600],[1774746000,1792890000,7200],[1792890000,1806195600,3600],[1806195600,1824944400,7200],[1824944400,1837645200,3600]];
                    var currentDateTimeSeconds = new Date().getTime() / 1000;
                    var timezoneOffset = 0;
                    for (var i=0; i &lt; timezoneOffsets.length; i ++) {
                        var zone = timezoneOffsets[i];
                        if (zone[0] &lt; currentDateTimeSeconds &amp;&amp; currentDateTimeSeconds &lt;= zone[1]) {
                            timezoneOffset = zone[2];
                            break;
                        }
                    }

                    var getOrderableTimes = function (startDay, startTime) {
                        var a = [];
                        for (var i=0; i&lt;orderableTimes.length; i++) {
                            var ot = orderableTimes[i];
                            ot = {day:ot.day, time_from:ot.time_from, time_until:ot.time_until};
...(length 27489)

2018-04-22 11:24:27.083 CEST Stacktrace
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/20180419t125107.409132121323748334/rogerthat/bizz/service/mfd/__init__.py", line 1256, in parse_message_flow_definition_set_xml
    mf_defs.build(parsexml_(StringIO(xml)).getroot())
  File "/base/data/home/apps/e~rogerthat-server/20180419t125107.409132121323748334/rogerthat/bizz/service/mfd/sub.py", line 62, in parsexml_
    doc = etree_.parse(*args, **kwargs)
  File "lxml.etree.pyx", line 2942, in lxml.etree.parse (third_party/apphosting/python/lxml/v2_3/src/lxml/lxml.etree.c:54187)
  File "parser.pxi", line 1545, in lxml.etree._parseDocument (third_party/apphosting/python/lxml/v2_3/src/lxml/lxml.etree.c:79661)
  File "parser.pxi", line 1573, in lxml.etree._parseMemoryDocument (third_party/apphosting/python/lxml/v2_3/src/lxml/lxml.etree.c:79932)
  File "parser.pxi", line 1452, in lxml.etree._parseDoc (third_party/apphosting/python/lxml/v2_3/src/lxml/lxml.etree.c:78774)
  File "parser.pxi", line 960, in lxml.etree._BaseParser._parseDoc (third_party/apphosting/python/lxml/v2_3/src/lxml/lxml.etree.c:75389)
  File "parser.pxi", line 564, in lxml.etree._ParserContext._handleParseResultDoc (third_party/apphosting/python/lxml/v2_3/src/lxml/lxml.etree.c:71739)
  File "parser.pxi", line 645, in lxml.etree._handleParseResult (third_party/apphosting/python/lxml/v2_3/src/lxml/lxml.etree.c:72614)
  File "parser.pxi", line 585, in lxml.etree._raiseParseError (third_party/apphosting/python/lxml/v2_3/src/lxml/lxml.etree.c:71955)
XMLSyntaxError: xmlParseEntityRef: no name, line 493, column 80


```

**Comment by RubenMattan** [comment]
Problem found, there was an unquoted & in the manual confirmation step
