### ISSUE TITLE
Failed to create order

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#932]
```python
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/20180424t113917.409246710421677010/mcfw/restapi.py", line 283, in run
    result = run(f, args, kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180424t113917.409246710421677010/mcfw/rpc.py", line 180, in run
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180424t113917.409246710421677010/mcfw/restapi.py", line 93, in wrapped
    return f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180424t113917.409246710421677010/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180424t113917.409246710421677010/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180424t113917.409246710421677010/shop/view.py", line 1605, in create_new_order
    create_order(customer_id, contact_id, items, replace, regio_manager_user=gusers.get_current_user())
  File "/base/data/home/apps/e~rogerthat-server/20180424t113917.409246710421677010/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180424t113917.409246710421677010/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180424t113917.409246710421677010/shop/bizz.py", line 452, in create_order
    product = all_products[item.product]
KeyError: u'FCTY'
```

```python
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/20180529t134853.410060501450369130/mcfw/restapi.py", line 283, in run
    result = run(f, args, kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180529t134853.410060501450369130/mcfw/rpc.py", line 180, in run
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180529t134853.410060501450369130/mcfw/restapi.py", line 93, in wrapped
    return f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180529t134853.410060501450369130/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180529t134853.410060501450369130/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180529t134853.410060501450369130/shop/view.py", line 1605, in create_new_order
    create_order(customer_id, contact_id, items, replace, regio_manager_user=gusers.get_current_user())
  File "/base/data/home/apps/e~rogerthat-server/20180529t134853.410060501450369130/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180529t134853.410060501450369130/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180529t134853.410060501450369130/shop/bizz.py", line 456, in create_order
    product = all_products[item.product]
KeyError: u'FREE'
```

**Comment by bart-at-mobicage** [comment]
I think I triggered the last one. Will be fixed once #878 is deployed.
Who triggered the first KeyError?

**Comment by RubenMattan** [comment]
Can't find any logs about the first error ...

**Comment by bart-at-mobicage** [comment]
ok, let's assume it's the same :D
