### ISSUE TITLE
Request loyalty devices failed

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#934]
```python
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/20180529t134853.410060501450369130/mcfw/restapi.py", line 283, in run
    result = run(f, args, kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180529t134853.410060501450369130/mcfw/rpc.py", line 180, in run
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180529t134853.410060501450369130/mcfw/restapi.py", line 93, in wrapped
    return f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180529t134853.410060501450369130/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180529t134853.410060501450369130/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180529t134853.410060501450369130/solutions/common/restapi/loyalty.py", line 593, in rest_request_loyalty_device
    request_loyalty_device(users.get_current_user(), source if source is not MISSING else None)
  File "/base/data/home/apps/e~rogerthat-server/20180529t134853.410060501450369130/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180529t134853.410060501450369130/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180529t134853.410060501450369130/solutions/common/bizz/loyalty.py", line 1860, in request_loyalty_device
    prospect = create_prospect_from_customer(customer)
  File "/base/data/home/apps/e~rogerthat-server/20180529t134853.410060501450369130/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180529t134853.410060501450369130/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180529t134853.410060501450369130/shop/business/prospect.py", line 191, in create_prospect_from_customer
    result = geo_code(prospect.address)
  File "/base/data/home/apps/e~rogerthat-server/20180529t134853.410060501450369130/rogerthat/utils/location.py", line 78, in geo_code
    raise GeoCodeStatusException(status)
GeoCodeStatusException: OVER_QUERY_LIMIT
```

**Comment by lucasvanhalst** [comment]
fixed by fdce13ecedc4463bfdaabcbce8bc8431819655df
