### ISSUE TITLE
OVER_QUERY_LIMIT when paying in the shop

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#939]
Can we defer the creation of the prospect? Or try_defer the geo_coding?

```
2018-06-06 18:52:07.381 CEST
[XX-OFFLOADv1]{"function":"/common/store/order/pay","status":false,"request_data":{},"timestamp":1528303927.3812101,"response_data":"OVER_QUERY_LIMIT","type":"web","user":"fc575c191563ffad8656dd75ff0d77ec"} (/base/data/home/apps/e~rogerthat-server/20180606t090006.410241445456628695/lib/log_offload/log_offload.py:58)

2018-06-06 18:52:07.381 CEST
OVER_QUERY_LIMIT (/base/data/home/apps/e~rogerthat-server/20180606t090006.410241445456628695/add_1_monkey_patches.py:128)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/20180606t090006.410241445456628695/mcfw/restapi.py", line 284, in run
    result = run(f, args, kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180606t090006.410241445456628695/mcfw/rpc.py", line 180, in run
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180606t090006.410241445456628695/mcfw/restapi.py", line 93, in wrapped
    return f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180606t090006.410241445456628695/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180606t090006.410241445456628695/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180606t090006.410241445456628695/solutions/common/restapi/store.py", line 392, in pay_order
    return db.run_in_transaction_options(xg_on, trans)
  File "/base/data/home/apps/e~rogerthat-server/20180606t090006.410241445456628695/add_1_monkey_patches.py", line 218, in wrapped
    r = run(transaction_guid)
  File "/base/data/home/apps/e~rogerthat-server/20180606t090006.410241445456628695/add_1_monkey_patches.py", line 198, in run
    return _orig_run_in_transaction_options(options, *args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/1/google/appengine/api/datastore.py", line 2635, in RunInTransactionOptions
    function, *args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/1/google/appengine/api/datastore.py", line 2710, in _RunInTransactionInternal
    ok, result = _DoOneTry(function, args, kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/1/google/appengine/api/datastore.py", line 2748, in _DoOneTry
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180606t090006.410241445456628695/solutions/common/restapi/store.py", line 385, in trans
    prospect = create_prospect_from_customer(customer)
  File "/base/data/home/apps/e~rogerthat-server/20180606t090006.410241445456628695/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180606t090006.410241445456628695/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180606t090006.410241445456628695/shop/business/prospect.py", line 191, in create_prospect_from_customer
    result = geo_code(prospect.address)
  File "/base/data/home/apps/e~rogerthat-server/20180606t090006.410241445456628695/rogerthat/utils/location.py", line 78, in geo_code
    raise GeoCodeStatusException(status)
GeoCodeStatusException: OVER_QUERY_LIMIT
```

**Comment by lucasvanhalst** [comment]
We should investigate why this happens, because you can send up to 100K requests per day

>  Once billing has been enabled, if you exceed 2,500 requests in a day, you will be billed at $0.50 USD / 1000 additional requests, up to 100,000 daily.

**Comment by bart-at-mobicage** [comment]
Using our API key in the `geo_code` method.

https://github.com/rogerthat-platform/rogerthat-backend/issues/513
