### ISSUE TITLE
NewsWizard is not defined in success handler of /common/get_menu

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#968]
NewsWizard is not defined?

```
2018-06-13 12:18:05 UTC
   (3 hour(s) ago)
service-ecc32b01-e320-4d23-a9ef-c9524ccb6d46@rogerth.at
Count: 1 - Version: web

description: Caught exception in success handler of /common/get_menu

errorMessage: NewsWizard is niet gedefinieerd
success@https://dashboard.onzestadapp.be/static/js/solutions/sln-news.js:36:21
   at options.success (https://dashboard.onzestadapp.be/static/js/solutions/sln-utils.js:1014:25)
c@https://dashboard.onzestadapp.be/static/js/jquery-1.10.0.min.js:4:25959
   at p.fireWith (https://dashboard.onzestadapp.be/static/js/jquery-1.10.0.min.js:4:26707)
k@https://dashboard.onzestadapp.be/static/js/jquery-1.10.0.min.js:6:14025
r@https://dashboard.onzestadapp.be/static/js/jquery-1.10.0.min.js:6:18415

mobicageVersion: web

occurenceCount: 1

platform: 0

platformVersion: Mozilla/5.0 (Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; MALC; wbx 1.0.0; rv:11.0) like Gecko
```

**Comment by lucasvanhalst** [comment]
so this means that is has loaded the sln-news.js file and finished the get_menu API call request inside sln-news.js BEFORE sln-news-wizard.js was loaded, even though that file should be loaded right after sln-news.js

**Comment by lucasvanhalst** [comment]
can't test this without using internet explorer
