### ISSUE TITLE
Error in city-select for country CDR

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#976]
```
2018-06-19 08:38:32 UTC
   (44 min ago)
service-e5d95a4d-a547-424e-904a-b8f969cd962a@rogerth.at (*** via shop)
Count: 1 - Version: web

description: Caught exception in 'click' handler of [object HTMLInputElement]

errorMessage: Cannot read property 'cities' of undefined
TypeError: Cannot read property 'cities' of undefined
    at ListCitySelect.getEnabledApps (https://rogerthat-server.appspot.com/static/js/solutions/sln-city-select.js:46:32)
    at ListCitySelect.cityAppsChanged [as onSelectionCompleted] (https://rogerthat-server.appspot.com/static/js/solutions/sln-news-wizard.js:1334:52)
    at ListCitySelect.setSelection (https://rogerthat-server.appspot.com/static/js/solutions/sln-city-select.js:350:10)
    at https://rogerthat-server.appspot.com/static/js/solutions/sln-news-wizard.js:536:37
    at initAppSelect (https://rogerthat-server.appspot.com/static/js/solutions/sln-news-wizard.js:1401:17)
    at HTMLInputElement.<anonymous> (https://rogerthat-server.appspot.com/static/js/solutions/sln-news-wizard.js:534:17)
    at HTMLInputElement.dispatch (https://rogerthat-server.appspot.com/static/js/jquery-1.10.0.min.js:5:13940)
    at HTMLInputElement.jQuery.event.dispatch (https://rogerthat-server.appspot.com/static/js/solutions/sln-utils.js:200:33)
    at HTMLInputElement.v.handle (https://rogerthat-server.appspot.com/static/js/jquery-1.10.0.min.js:5:10677)

mobicageVersion: web

occurenceCount: 1

platform: 0

platformVersion: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36

```

```
2018-06-19 08:38:32 UTC
   (44 min ago)
service-e5d95a4d-a547-424e-904a-b8f969cd962a@rogerth.at (*** via shop)
Count: 1 - Version: web

description: Caught exception in global scope: Uncaught TypeError: Cannot read property 'cities' of undefined

errorMessage: Cannot read property 'cities' of undefined
in https://rogerthat-server.appspot.com/static/js/solutions/sln-utils.js at line 203:9
TypeError: Cannot read property 'cities' of undefined
    at ListCitySelect.getEnabledApps (https://rogerthat-server.appspot.com/static/js/solutions/sln-city-select.js:46:32)
    at ListCitySelect.cityAppsChanged [as onSelectionCompleted] (https://rogerthat-server.appspot.com/static/js/solutions/sln-news-wizard.js:1334:52)
    at ListCitySelect.setSelection (https://rogerthat-server.appspot.com/static/js/solutions/sln-city-select.js:350:10)
    at https://rogerthat-server.appspot.com/static/js/solutions/sln-news-wizard.js:536:37
    at initAppSelect (https://rogerthat-server.appspot.com/static/js/solutions/sln-news-wizard.js:1401:17)
    at HTMLInputElement.<anonymous> (https://rogerthat-server.appspot.com/static/js/solutions/sln-news-wizard.js:534:17)
    at HTMLInputElement.dispatch (https://rogerthat-server.appspot.com/static/js/jquery-1.10.0.min.js:5:13940)
    at HTMLInputElement.jQuery.event.dispatch (https://rogerthat-server.appspot.com/static/js/solutions/sln-utils.js:200:33)
    at HTMLInputElement.v.handle (https://rogerthat-server.appspot.com/static/js/jquery-1.10.0.min.js:5:10677)

mobicageVersion: web

occurenceCount: 1

platform: 0

platformVersion: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36

```

**Comment by bart-at-mobicage** [comment]
- [ ] merchants of country CDR see 2 demo apps in the city select. They shouldn't see them.
- [ ] let's hide the local/regional options (just like we do if regional news is not enabled, eg. for enterprise apps) in case there are no other cities to select.

![screen shot 2018-06-22 at 09](https://user-images.githubusercontent.com/17762105/41771777-79153e80-7616-11e8-8137-eaf8d02abed5.png)
